Minor spelling
toniblyx/prowler pull request #1008
Opened 2022-01-28 23:15 UTC by sectoramen

### Context 

Minor spelling fixes

### Description

Fixed a few spelling mistrakes

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-01-28 23:16 UTC, sectoramen commented
Fixed a few minor spelling I noticed while going through the ReadMe

2022-01-31 08:20 UTC, jfagoagas requested changes
Thank you for this review @sectoramen 

Please check the above comments in order to merge!

2022-01-31 08:20 UTC, jfagoagas commented on README.md
> +    ```eachg
Is this a typo?

2022-01-31 08:20 UTC, jfagoagas commented on README.md
> +    ```eachg sh
Also this.

2022-02-05 20:44 UTC, sectoramen commented
Fixed typos

2022-02-07 08:12 UTC, jfagoagas approved these changes
Thanks @sectoramen

2022-02-07 08:13 UTC, merged