fix(check41/42): Added tcp protocol filter to query
toniblyx/prowler pull request #1035
Opened 2022-02-08 07:57 UTC by n4ch04

### Context 

Check41 and Check42 returns false positives when gre protocol rule is included in sg 

### Description

When working with check41 and check42 some false positives rose up due to not including protocol filtering

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-08 08:05 UTC, jfagoagas requested changes
Good job @n4ch04, please check above comments in order to merge this PR.

2022-02-08 08:05 UTC, jfagoagas commented on checks/check41
> +    SG_LIST=$($AWSCLI ec2 describe-security-groups --query 'SecurityGroups[?length(IpPermissions[?((FromPort==null && ToPort==null) || (FromPort<=`22` && ToPort>=`22`)) && (contains(IpRanges[].CidrIp
```suggestion
    SG_LIST=$("${AWSCLI}" ec2 describe-security-groups --query 'SecurityGroups[?length(IpPermissions[?((FromPort==null && ToPort==null) || (FromPort<=`22` && ToPort>=`22`)) && (contains(IpRanges[].CidrIp, `0.0.0.0/0`) || contains(Ipv6Ranges[].CidrIpv6, `::/0`)) && (IpProtocol==`tcp`)]) > `0`].{GroupId:GroupId}' $PROFILE_OPT --region "${regx}" --output text 2>&1)
```

2022-02-08 08:05 UTC, jfagoagas commented on checks/check42
> +    SG_LIST=$($AWSCLI ec2 describe-security-groups --query 'SecurityGroups[?length(IpPermissions[?((FromPort==null && ToPort==null) || (FromPort<=`3389` && ToPort>=`3389`)) && (contains(IpRanges[].Ci
```suggestion
    SG_LIST=$("${AWSCLI}" ec2 describe-security-groups --query 'SecurityGroups[?length(IpPermissions[?((FromPort==null && ToPort==null) || (FromPort<=`3389` && ToPort>=`3389`)) && (contains(IpRanges[].CidrIp, `0.0.0.0/0`) || contains(Ipv6Ranges[].CidrIpv6, `::/0`)) && (IpProtocol==`tcp`) ]) > `0`].{GroupId:GroupId}' $PROFILE_OPT --region "${regx}" --output text 2>&1)
```

2022-02-08 13:47 UTC, toniblyx submitted a review, later dismissed

2022-02-08 15:47 UTC, jfagoagas approved these changes
Good job @n4ch04

2022-02-09 15:08 UTC, toniblyx approved these changes

2022-02-10 23:00 UTC, StephenKing commented
LGTM, very much appreciated!

2022-02-11 09:54 UTC, merged