fix(include/outputs):Rolling back whitelist checking to RE check
toniblyx/prowler pull request #1037
Opened 2022-02-08 12:38 UTC by n4ch04

### Context 

With last change to exactly match elements included in the whitelist and log info returned whitelist feature was broken not whitelisting multitude of items

### Description

Fix the feature, rolling back to regular expression checking to find if whitelisted element is included into log message

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-02-08 13:48 UTC, toniblyx approved these changes, later dismissed
LGTM

2022-02-08 15:37 UTC, jfagoagas requested changes

2022-02-08 15:37 UTC, jfagoagas commented on include/outputs
> +    checked_value=$1
Please link `$1` with local variable with a proper name to better follow the execution flow.

Also, quote variables --> `"${varName}"`

2022-02-08 15:48 UTC, jfagoagas approved these changes
LGTM

2022-02-09 14:54 UTC, toniblyx approved these changes

2022-02-14 12:04 UTC, merged