fix(extra715): Change lower case from bash variable expansion to tr
toniblyx/prowler pull request #1064
Opened 2022-03-09 11:47 UTC by lazize

### Context 

Bash variable expansion doesn't work on old bash version from macOS

### Description

Change lower case transformation from bash variable expansion to `tr '[:upper:]' '[:lower:]'` command.
Fix issue #1058 

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-09 14:47 UTC, lazize commented
extra715
extra780
extra785
extra7101
check_sample

2022-03-14 10:08 UTC, n4ch04 requested changes

2022-03-14 10:08 UTC, n4ch04 commented on checks/check_extra7101
> +        if [[ $(echo "${AUDIT_LOGS_ENABLED}" | tr '[:upper:]' '[:lower:]') == "true" ]]; then
Could you change this to 
`tr '[:upper:]' '[:lower:]' <<< "${AUDIT_LOGS_ENABLED}"`

2022-03-14 10:08 UTC, n4ch04 commented on checks/check_extra715
> +          if [[ $(echo "${SEARCH_SLOWLOG_ENABLED}" | tr '[:upper:]' '[:lower:]') == "true" ]]; then
Same as in previous
`tr '[:upper:]' '[:lower:]' <<< "${SEARCH_SLOWLOG_ENABLED}"`

2022-03-14 10:08 UTC, n4ch04 commented on checks/check_extra715
> +          if [[ $(echo "${SEARCH_SLOWLOG_ENABLED}" | tr '[:upper:]' '[:lower:]') == "true" ]]; then
Same as in previous
`tr '[:upper:]' '[:lower:]' <<< "${SEARCH_SLOWLOG_ENABLED}"`

2022-03-14 10:08 UTC, n4ch04 commented on checks/check_extra715
> +          if [[ $(echo "${INDEX_SLOWLOG_ENABLED}" | tr '[:upper:]' '[:lower:]') == "true" ]]; then
Same as in previous 
`tr '[:upper:]' '[:lower:]' <<< "${INDEX_SLOWLOG_ENABLED}"`

2022-03-14 10:08 UTC, n4ch04 commented on checks/check_extra715
> +          if [[ $(echo "${INDEX_SLOWLOG_ENABLED}" | tr '[:upper:]' '[:lower:]') == "true" ]]; then
Same as in previous 
`tr '[:upper:]' '[:lower:]' <<< "${INDEX_SLOWLOG_ENABLED}"`

2022-03-14 10:08 UTC, n4ch04 commented on checks/check_extra780
> +        if [[ $(echo "${CHECK_IF_COGNITO_ENABLED}" | tr '[:upper:]' '[:lower:]') == "true" ]]; then
Same as in previous
`tr '[:upper:]' '[:lower:]' <<< "${CHECK_IF_COGNITO_ENABLED}"`

2022-03-14 10:08 UTC, n4ch04 commented on checks/check_extra780
> +        if [[ $(echo "${CHECK_IF_COGNITO_ENABLED}" | tr '[:upper:]' '[:lower:]') == "true" ]]; then
Same as in previous
tr '[:upper:]' '[:lower:]' <<< "${CHECK_IF_COGNITO_ENABLED}"

2022-03-14 10:08 UTC, n4ch04 commented on checks/check_extra785
> +        if [[ $(echo "${update_status}" | tr '[:upper:]' '[:lower:]') != "false" ]]; then
Same as in previous: 
`tr '[:upper:]' '[:lower:]' <<< "${CHECK_IF_COGNITO_ENABLED}"`

2022-03-14 10:08 UTC, n4ch04 commented on checks/check_extra785
> +        if [[ $(echo "${update_status}" | tr '[:upper:]' '[:lower:]') != "false" ]]; then
Same as in previous: 
`tr '[:upper:]' '[:lower:]' <<< "${CHECK_IF_COGNITO_ENABLED}"`

2022-03-14 10:10 UTC, n4ch04 commented
@lazize, I have requested a few changes more related with the style we are using in the project, please check it out and thank you for your contribution !!

2022-03-15 07:21 UTC, n4ch04 approved these changes

2022-03-15 07:21 UTC, n4ch04 commented on checks/check_extra7101
> +        if [[ $(echo "${AUDIT_LOGS_ENABLED}" | tr '[:upper:]' '[:lower:]') == "true" ]]; then
Could you change this to 
`tr '[:upper:]' '[:lower:]' <<< "${AUDIT_LOGS_ENABLED}"`

2022-03-15 07:22 UTC, merged

2022-03-15 07:22 UTC, n4ch04 commented
Thanks for all !! @lazize