Fix(check122): Error when policy name contains commas
toniblyx/prowler pull request #1067
Opened 2022-03-14 21:10 UTC by plarso

### Context 

AWS IAM policy names allow commas (','), but check 122 does not support the case where there is a comma in the policy name.

### Description

* Change the awk command for the POLICY_VERSION variable in the script to get the version number from the last column rather than the second column.
* Change the awk command for the POLICY_ARN variable in the script to get the policy ARN from all columns except the last instead of just the first column.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-15 07:20 UTC, jfagoagas requested changes
Thanks @plarso, please review comments above to merge this PR!

2022-03-15 07:20 UTC, jfagoagas commented on checks/check122
> +      POLICY_ARN=$(echo $policy | awk 'BEGIN{FS=OFS=","}{NF--; print}')
```suggestion
      POLICY_ARN=$(awk 'BEGIN{FS=OFS=","}{NF--; print}' <<< "${policy}")
```

2022-03-15 07:20 UTC, jfagoagas commented on checks/check122
> +      POLICY_VERSION=$(echo $policy | awk -F ',' '{print $(NF)}')
```suggestion
      POLICY_VERSION=$(awk -F ',' '{print $(NF)}' <<< "${policy}")
```

2022-03-15 10:17 UTC, lazize commented
If it has comma, it will break csv output.
If it is allowed by AWS, we should replace it by something else.

2022-03-15 15:51 UTC, jfagoagas commented
> If it has comma, it will break csv output. If it is allowed by AWS, we should replace it by something else.

Good point! I'm going to test a initial approach to solve this.

2022-03-15 17:05 UTC, jfagoagas commented
Hi @plarso could you include the following as a replace in line 42?
```
textFail "$REGION: Policy ${policy/,/comma} allows \"*:*\"" "$REGION" "$policy"
```

This is a valid approach but we are modifying role name in the output.

1. AWS Test Roles
<img width="863" alt="Screenshot 2022-03-15 at 17 55 30" src="https://user-images.githubusercontent.com/16007882/158432327-0da43364-7342-4f5c-ba01-16c67c79515b.png">
2. Prowler Result
<img width="1035" alt="Screenshot 2022-03-15 at 17 55 58" src="https://user-images.githubusercontent.com/16007882/158432368-55473140-2af7-4c91-b7d8-b5d035fdb4e8.png">

Also @lazize please check this.

Thanks!

2022-03-15 18:05 UTC, plarso commented on checks/check122
> +      POLICY_VERSION=$(echo $policy | awk -F ',' '{print $(NF)}')
Suggestion implemented in new commit.

2022-03-15 18:05 UTC, plarso commented on checks/check122
> +      POLICY_ARN=$(echo $policy | awk 'BEGIN{FS=OFS=","}{NF--; print}')
Suggestion implemented in new commit.

2022-03-15 18:06 UTC, plarso commented
I've added the requested changes.

2022-03-16 00:45 UTC, lazize commented
Based on my recent experience, I believe this kind of variable expansion will not be supported by old version of bash, like the one original from macOS.
I will test it tomorrow.

2022-03-16 07:16 UTC, jfagoagas commented
> I've added the requested changes.

Cool, thank you @plarso !

2022-03-16 07:17 UTC, jfagoagas commented
> Based on my recent experience, I believe this kind of variable expansion will not be supported by old version of bash, like the one original from macOS.
> 
> I will test it tomorrow.

All of this changes has been tested with `Bash 3.15`, this kind of variable expansion is supported in old versions of Bash.

2022-03-16 14:06 UTC, jfagoagas approved these changes
Good job @plarso !!

Thanks 👏

2022-03-16 14:06 UTC, merged