fix(bucket_region): check extra764 doesn't handle bucket region properly
toniblyx/prowler pull request #1077
Opened 2022-03-17 15:44 UTC by sergargar

### Context 

When running the check extra764 for S3 it picks up the global region instead of the region the bucket is created in.

### Description

Return the correct region as it has done for the rest S3 checks.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-17 15:54 UTC, jfagoagas requested changes
Good job, please check above comments.

2022-03-17 15:54 UTC, jfagoagas commented on checks/check_extra764
> +      if grep AccessDenied <<< "${BUCKET_LOCATION}"; then
```suggestion
      if grep -q -E 'AccessDenied|UnauthorizedOperation|AuthorizationError' <<< "${BUCKET_LOCATION}"; then
```

2022-03-17 15:54 UTC, jfagoagas commented on checks/check_extra764
> +      $AWSCLI s3api get-bucket-policy $PROFILE_OPT --bucket "${bucket}" --output text --query Policy --region "${BUCKET_LOCATION}" > "${TEMP_STP_POLICY_FILE}" 2>&1
```suggestion
      TEMP_STP_POLICY_FILE="${AWSCLI}" s3api get-bucket-policy ${PROFILE_OPT} --bucket "${bucket}" --output text --query Policy --region "${BUCKET_LOCATION}" 2>&1
```

2022-03-17 15:54 UTC, jfagoagas commented on checks/check_extra764
> +      if grep AccessDenied <<< "${TEMP_STP_POLICY_FILE}"; then
```suggestion
      if grep -q -E 'AccessDenied|UnauthorizedOperation|AuthorizationError' <<< "${TEMP_STP_POLICY_FILE}"; then
```

2022-03-17 15:54 UTC, jfagoagas commented on checks/check_extra764
>        if [[ $(grep NoSuchBucketPolicy $TEMP_STP_POLICY_FILE) ]]; then
```suggestion
      if grep -q "NoSuchBucketPolicy" <<< $TEMP_STP_POLICY_FILE) ; then
```

2022-03-17 15:54 UTC, jfagoagas commented on checks/check_extra764
> +      if jq -e . >/dev/null 2>&1 <<< "${policy_str}"; then
I think this line is not needed.
```suggestion
      if jq -e . >/dev/null 2>&1 <<< "${TEMP_STP_POLICY_FILE}"; then
```

2022-03-17 15:54 UTC, jfagoagas commented on checks/check_extra764
> +          textInfo "Unknown Error occurred: ${policy_str}"
```suggestion
          textInfo "Unknown Error occurred: ${TEMP_STP_POLICY_FILE}"
```

2022-03-17 16:14 UTC, jfagoagas approved these changes
Good job @sergargar

2022-03-18 10:51 UTC, toniblyx approved these changes

2022-03-18 10:51 UTC, merged