feat(S3_in_w_x_flags): Support S3 URIs for custom checks paths and whitelist files.
toniblyx/prowler pull request #1090
Opened 2022-03-30 12:20 UTC by sergargar

### Context 

This new feature will allow users to input S3 URIs when working with whitelists (-w flag) or custom checks paths (-x flag).

### Description

If an user input a S3 URI in flags -w or -x, Prowler will automatically read the files from the indicated S3 bucket.
For example:
./prowler -c extra764 -p <profile_name> -w s3://bucket/whitelist.txt
./prowler -c extra764 -p <profile_name> -x s3://bucket/checks

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-31 12:09 UTC, toniblyx requested changes

2022-03-31 12:09 UTC, toniblyx commented on README.md
> +    To save your report in an S3 bucket, use `-B` to define a custom output bucket along with `-M` to defiine the output format that is going to be updated to S3:
```suggestion
    To save your report in an S3 bucket, use `-B` to define a custom output bucket along with `-M` to define the output format that is going to be uploaded to S3:
```

2022-03-31 12:09 UTC, toniblyx commented on README.md
> +S3 URIs are also supported as custom folders for custom checks, e.g. `s3://bucket/prefix/checks`
```suggestion
S3 URIs are also supported as custom folders for custom checks, e.g. `s3://bucket/prefix/checks`. Prowler will download the folder locally and run the checks as they are called with default execution,`-c` or `-g`.
```

2022-03-31 12:09 UTC, toniblyx commented on include/custom_checks
> +#!/usr/bin/env bash
every message that starts by $OK or $BAD to colorize the output must be clean up after each sentence with $NORMAL. So, for instance `echo -e "$OK Success! Custom checks were downloaded and included, starting Prowler..."` must actually be `echo -e "$OK Success! Custom checks were downloaded and included, starting Prowler...$NORMAL"`

2022-03-31 12:29 UTC, jfagoagas requested changes
Good job! Please check my comments above.

As a general comment, review variable braces `{}`

2022-03-31 12:29 UTC, jfagoagas commented on include/allowlist
> +    if ! $AWSCLI s3 cp $ALLOWLIST_FILE allowlist_s3_file.txt $PROFILE_OPT > /dev/null 2>&1; then
Please, include `allowlist_s3_file.txt` as a local variable like:
```sh
local ALLOWLIST_S3_FILE=allowlist_s3_file.txt
```

Maybe you can use `ALLOWLIST_S3_FILE` and `ALLOWLIST_LOCAL_FILE`

2022-03-31 12:29 UTC, jfagoagas commented on include/allowlist
> +    ALLOWLIST_FILE=allowlist_s3_file.txt
This temporary file could be a local variable

2022-03-31 12:29 UTC, jfagoagas commented on include/allowlist
> +      ALLOWLIST=$(awk '!/^[[:space:]]*#/{print }' <(cat "$ALLOWLIST_FILE") | sed 's/[[:space:]]*#.*$//g')
Think about the following logic:
1. Check if there is an input whitelist, from a local file or from S3
2. Load `ALLOWLIST` variable with the allowed resources.

Only an opinion to reduce some lines.

2022-03-31 12:29 UTC, jfagoagas commented on include/custom_checks
> +    if grep -q "check*" <<< "$($AWSCLI s3 ls "$EXTERNAL_CHECKS_PATH" $PROFILE_OPT)"; then
```suggestion
    if grep -q "check*" <<< "$("${AWSCLI}" s3 ls "${EXTERNAL_CHECKS_PATH}" ${PROFILE_OPT})"; then
```

2022-03-31 12:29 UTC, jfagoagas commented on include/custom_checks
> +    rm -rf "${S3_CHECKS_TEMP_FOLDER}"
Can you remove the custom checks folder prior to start the execution of this checks?

2022-03-31 12:29 UTC, jfagoagas commented on include/custom_checks
> +        echo -e "$OK Check $(basename "$checks") was included!$NORMAL"
Same here, think about first recovering checks and then a unique load.

2022-03-31 13:41 UTC, jfagoagas commented
Do we need to include required AWS S3 API permissions?

2022-03-31 14:56 UTC, sergargar commented
> Do we need to include required AWS S3 API permissions?

Review the last commit with those changes pls.

2022-03-31 15:19 UTC, jfagoagas approved these changes
🎉 🎉 🎉 🎉 🎉 🎉 🎉 🎉 

New features!! 👏

2022-04-07 18:36 UTC, toniblyx approved these changes
LGTM

2022-04-07 18:37 UTC, merged