Update CloudFormation template for CodeBuild
toniblyx/prowler pull request #1114
Opened 2022-04-26 21:00 UTC by jplock

### Context 

Cloudformation template updates to conform to best practices and simplifications

### Description

- Updated Lambda function runtime from `python3.6` to `python3.9` due to python 3.6 being deprecated
- Create explicit log group for `CodeBuildStartBuildLambda` so retention can be set
- Fix cyclical dependency issues with `CodeBuildServiceRole` to remove explicit role name
- Use `${AWS::Partition}` to support multiple AWS partitions
- Update CodeBuild project to pull source from GitHub instead of in buildspec
- Remove `ProwlerScheduleLambdaFunction` in favor of having EventBridge start the CodeBuild project
- Remove installing AWS CLI v2 (and `jq`) as they are already available on the build image

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-04-29 08:26 UTC, sergargar requested changes
Hi @jplock, thank you for this great contribution!
However, it is a good practice to verity cfn templates with `cfn_nag`, could you please execute it and suppress the rest of the rules like I did (or change the code if needed)?

2022-04-29 08:26 UTC, sergargar commented on util/codebuild/codebuild-prowler-audit-account-cfn.yaml
>      Type: 'AWS::Lambda::Function'
```suggestion
    Type: 'AWS::Lambda::Function'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W58
            reason: "This Lambda has permissions to write Logs"
          - id: W92
            reason: "ReservedConcurrentExecutions not needed"
```

2022-04-29 08:26 UTC, sergargar commented on util/codebuild/codebuild-prowler-audit-account-cfn.yaml
> +    Type: 'AWS::Logs::LogGroup'
```suggestion
    Type: 'AWS::Logs::LogGroup'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W84
            reason: "KMS encryption is not needed."
```

2022-04-29 08:26 UTC, sergargar commented on util/codebuild/codebuild-prowler-audit-account-cfn.yaml
>      Type: AWS::S3::Bucket
```suggestion
    Type: AWS::S3::Bucket
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: "S3 Access Logging is not needed."
```

2022-04-29 08:26 UTC, sergargar commented on util/codebuild/codebuild-prowler-audit-account-cfn.yaml
>      Type: AWS::IAM::Role
```suggestion
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Role complies with the least privilege principle."
```

2022-04-29 08:26 UTC, sergargar commented on util/codebuild/codebuild-prowler-audit-account-cfn.yaml
>      Type: 'AWS::Logs::LogGroup'
```suggestion
    Type: 'AWS::Logs::LogGroup'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W84
            reason: "KMS encryption is not needed."
```

2022-04-29 13:43 UTC, jplock commented
Thanks for the review @sergargar!  I added the cfn-nag rule suppressions.

2022-05-03 07:14 UTC, sergargar commented
Thank you @jplock !

2022-05-03 07:14 UTC, sergargar approved these changes

2022-05-03 07:14 UTC, merged