fix(custom-file-in-bucket): Custom file names are also support for S3 output.
toniblyx/prowler pull request #1129
Opened 2022-05-09 13:06 UTC by sergargar

### Context 

Custom file names were not applied to S3 bucket uploads. (flag -F was not applicable to -D/B)

### Description

Include custom file names as well when exporting prowler reports to S3.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-05-09 13:53 UTC, jfagoagas requested changes
Check comments and inspect the following:
```
initCopyToS3() {
  # Prowler will copy each format to its own folder in S3, that is for better handling 
  # and processing by Quicksight or others.
  
  # Also, check if -F was introduced
  if [ -n "${OUTPUT_FILE_NAME+x}" ]; then
    OUTPUT_PATH="${OUTPUT_FILE_NAME}"
  else
    OUTPUT_PATH="$OUTPUT_DIR/prowler-output-${ACCOUNT_NUM}-${OUTPUT_DATE}"
  fi

  for output_format in "${MODES[@]}";
  do
    case ${output_format} in
      csv)
        copyToS3 "${OUTPUT_PATH}" "${EXTENSION_CSV}"
      ;;
      html)
        copyToS3 "${OUTPUT_PATH}" "${EXTENSION_HTML}"
      ;;
      json)
        copyToS3 "${OUTPUT_PATH}" "${EXTENSION_JSON}"
      ;;
      json-asff)
        copyToS3 "${OUTPUT_PATH}" "${EXTENSION_ASFF}"
      ;;
      *)
        echo "$OPTRED ERROR!$OPTNORMAL - Invalid output format copying to S3. Use -h for help."
        exit 1
      ;;
    esac
  done
}

copyToS3(){
  OUTPUT_PATH="${1}"
  EXTENSION="${2}"
  "${AWSCLI}" ${PROFILE_OPT} s3 cp "${OUTPUT_PATH}.${EXTENSION}" s3://"${OUTPUT_BUCKET}"/${EXTENSION}/ --acl bucket-owner-full-control
}
```

2022-05-09 13:53 UTC, jfagoagas commented on include/outputs_bucket
> +    if [[ $OUTPUT_BUCKET ]]; then
Do you need this comparison? I think this function is called if `$OUTPUT_BUCKET` is passed as option.

2022-05-09 13:53 UTC, jfagoagas commented on include/outputs_bucket
> +    if [[ $OUTPUT_BUCKET ]]; then
Same as above.

2022-05-09 15:52 UTC, sergargar commented
> Check comments and inspect the following:
> 
> ```
> copyToS3() {
>   # Prowler will copy each format to its own folder in S3, that is for better handling 
>   # and processing by Quicksight or others.
> 
>   # Also, check if -F was introduced
>   if [ -n "${OUTPUT_FILE_NAME+x}" ]; then
>     OUTPUT_PATH="${OUTPUT_FILE_NAME}"
>   else
>     OUTPUT_PATH="$OUTPUT_DIR/prowler-output-${ACCOUNT_NUM}-${OUTPUT_DATE}"
>   fi
> 
>   for output_format in "${MODES[@]}";
>   do
>     case ${output_format} in
>       csv)
>         s3cp "${OUTPUT_PATH}" "${EXTENSION_CSV}"
>       ;;
>       html)
>         s3cp "${OUTPUT_PATH}" "${EXTENSION_HTML}"
>       ;;
>       json)
>         s3cp "${OUTPUT_PATH}" "${EXTENSION_JSON}"
>       ;;
>       json-asff)
>         s3cp "${OUTPUT_PATH}" "${EXTENSION_ASFF}"
>       ;;
>       *)
>         echo "$OPTRED ERROR!$OPTNORMAL - Invalid output format copying to S3. Use -h for help."
>         exit 1
>       ;;
>     esac
>   done
> }
> 
> s3cp(){
>   OUTPUT_PATH="${1}"
>   EXTENSION="${2}"
>   "${AWSCLI}" ${PROFILE_OPT} s3 cp "${OUTPUT_PATH}.${EXTENSION}" s3://"${OUTPUT_BUCKET}"/${EXTENSION}/ --acl bucket-owner-full-control
> }
> ```

I love it! Thank you @jfagoagas

2022-05-11 07:36 UTC, jfagoagas requested changes

2022-05-11 07:36 UTC, jfagoagas commented on include/outputs_bucket
> +    OUTPUT_PATH="${OUTPUT_FILE_NAME}"
What if we are using `-o` to specify a custom output folder?

Maybe we need something like this:
```
# Default OUTPUT_DIR value is "${PROWLER_DIR}/output"
local S3_FOLDER
if [ -n "${OUTPUT_DIR_CUSTOM}" ]; then
   S3_FOLDER="${OUTPUT_DIR_CUSTOM}"
else
    S3_FOLDER="${OUTPUT_DIR}"
fi

local S3_OUTPUT_PATH
if [ -n "${OUTPUT_FILE_NAME+x}" ]; then
    S3_OUTPUT_PATH="${S3_FOLDER}/${OUTPUT_FILE_NAME}"
else
    S3_OUTPUT_PATH="${S3_FOLDER}/prowler-output-${ACCOUNT_NUM}-${OUTPUT_DATE}"
fi
```

2022-05-11 08:13 UTC, sergargar commented on include/outputs_bucket
> +    OUTPUT_PATH="${OUTPUT_FILE_NAME}"
That is not necessary since the user can introduce an entire S3 URI with `-D`, which is stored in `OUTPUT_BUCKET` variable.

2022-05-11 08:16 UTC, jfagoagas approved these changes
Awesome!!! 

A really good fix here.

2022-05-11 08:16 UTC, merged