feat(checks): Select checks to run from provider
toniblyx/prowler pull request #1197
Opened 2022-06-14 13:11 UTC by jfagoagas

### Context 

We need to launch checks passing its names using `-c/--checks` based on the selected provider.

### Description

This PR includes the feature to run checks using `-c/--checks`. It also validates the existence of the check within the provider.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-15 11:52 UTC, sergargar commented on providers/aws/services/iam/iam_disable_30_days_credentials/iam_disable_30_days_credentials.py
>              report.region = "us-east-1"
```suggestion
            report.region = "us-east-1"
            findings.append(report)
```

2022-06-15 11:53 UTC, sergargar requested changes
Amazing work!!

2022-06-15 11:54 UTC, sergargar approved these changes

2022-06-16 10:19 UTC, n4ch04 approved these changes

2022-06-16 10:20 UTC, merged