feat(json-asff): add json-asff ouput
toniblyx/prowler pull request #1252
Opened 2022-07-06 11:43 UTC by sergargar

### Context 

Add feature to create Json ASFF output.

### Description

- Include JSON ASFF model with Pydantic and functionalities to create output Json ASFF files.
- Modify Check Metadata model with Pydantic

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-07-07 09:00 UTC, jfagoagas requested changes
Good job @sergargar

2022-07-07 09:00 UTC, jfagoagas commented on config/config.py
> +json_asff_file_suffix = timestamp.strftime("%Y%m%d%H%M%S") + "asff.json"
```suggestion
output_file_timestamp = timestamp.strftime("%Y%m%d%H%M%S")
csv_file_suffix = f"{output_file_timestamp}.csv"
json_file_suffix = f"{output_file_timestamp}.json"
json_asff_file_suffix = f"{output_file_timestamp}.asff.json"
```

2022-07-07 09:00 UTC, jfagoagas commented on lib/check/models.py
> +
👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏 👏

2022-07-07 09:00 UTC, jfagoagas commented on lib/check/models.py
> +    other: str
Why `cli` and `other` are lowercase?

2022-07-07 09:00 UTC, jfagoagas commented on lib/outputs/models.py
> +    ProductFields: ProductFields = None
Why this is None?

2022-07-07 09:00 UTC, jfagoagas commented on lib/outputs/outputs.py
> +
Think about merging the `json` and `json-asff` logic because 80% of this code is the same

2022-07-07 09:00 UTC, jfagoagas commented on lib/outputs/outputs.py
> +        filename = f"{output_directory}/prowler-output-{audited_account}-{json_asff_file_suffix}"
Same here

2022-07-07 09:04 UTC, sergargar commented on lib/outputs/models.py
> +    ProductFields: ProductFields = None
Because I have to initialize it and the default parameters are also stored.

2022-07-07 09:05 UTC, sergargar commented on lib/check/models.py
> +    other: str
Done

2022-07-07 09:21 UTC, jfagoagas commented on lib/check/models.py
> +    Cli: str
I prefer `CLI`, what do you think?
```suggestion
    CLI: str
```

2022-07-07 09:22 UTC, jfagoagas commented on lib/outputs/models.py
> +    ProductFields: ProductFields = None
Good then

2022-07-08 07:37 UTC, jfagoagas approved these changes
Well done!!

2022-07-08 07:37 UTC, merged