Prwlr 815 check developing iam password policy uppercase
toniblyx/prowler pull request #1364
Opened 2022-09-09 12:21 UTC by n4ch04

### Context 

Migrate from prowler 2.X to prowler 3 for checks regarding password policy, which are:

- providers/aws/services/iam/iam_password_policy_lowercase
- providers/aws/services/iam/iam_password_policy_minimum_length_14
- providers/aws/services/iam/iam_password_policy_number
- providers/aws/services/iam/iam_password_policy_reuse_24
- providers/aws/services/iam/iam_password_policy_symbol
- providers/aws/services/iam/iam_password_policy_uppercase

Since it is the same logic for all with really small changes all are included in a PR

### Description

Migrate from prowler 2.X to prowler 3 for checks regarding password policy, which are:

- providers/aws/services/iam/iam_password_policy_lowercase
- providers/aws/services/iam/iam_password_policy_minimum_length_14
- providers/aws/services/iam/iam_password_policy_number
- providers/aws/services/iam/iam_password_policy_reuse_24
- providers/aws/services/iam/iam_password_policy_symbol
- providers/aws/services/iam/iam_password_policy_uppercase

Since it is the same logic for all with really small changes all are included in a PR

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-12 06:07 UTC, jfagoagas requested changes
Good job @n4ch04, as an overall comments about the checks:
- We have to include the `logger` and some `try-except` clause to handle unexpected errors.
- We need to include more tests than the obvious ones for example empty responses

2022-10-17 10:24 UTC, n4ch04 commented
Since we have talk, we are not going to include the `try - except` on each check and include more detail into the exceptions catches, the same applies to empty responses

2022-10-18 07:48 UTC, jfagoagas approved these changes
Great job @n4ch04, please review the suggestions prior to merge, thanks!

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_minimum_length_14/iam_password_policy_minimum_length_14.metadata.json
> +      "Text": "Ensure \"Minimum password length\" is checked under \"Password Policy\"..",
```suggestion
      "Text": "Ensure \"Minimum password length\" is checked under \"Password Policy\".",
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_minimum_length_14/iam_password_policy_minimum_length_14.py
> +            # Check if symbol flag is set
```suggestion
            # Check password policy length
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_number/iam_password_policy_number.metadata.json
> +      "Text": "Ensure \"Require at least one number\" is checked under \"Password Policy\"..",
```suggestion
      "Text": "Ensure \"Require at least one number\" is checked under \"Password Policy\".",
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_number/iam_password_policy_number.py
> +                    f"Password number option in password policy is set."
```suggestion
                    "IAM password policy require at least one number."
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_number/iam_password_policy_number.py
> +                    f"Password number option in password policy is not set."
```suggestion
                    "IAM password policy does not require at least one number"
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_number/iam_password_policy_number.py
> +            report.status_extended = f"Password policy cannot be found"
```suggestion
            report.status_extended = "There is no password policy."
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_minimum_length_14/iam_password_policy_minimum_length_14.py
> +                report.status_extended = f"Password minimum length in password policy requires more than 13 characters."
```suggestion
                report.status_extended = "IAM password policy requires minimum length of 14 characters."
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_minimum_length_14/iam_password_policy_minimum_length_14.py
> +                report.status_extended = f"Password minimum length in password policy requires less than 13 characters or not set."
```suggestion
                report.status_extended = "IAM password policy does not requires minimum length of 14 characters."
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_lowercase/iam_password_policy_lowercase.py
> +                    f"Password lowercase option in password policy is set."
```suggestion
                    "IAM password policy require at least one lowercase letter."
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_lowercase/iam_password_policy_lowercase.py
> +                    f"Password lowercase option in password policy is not set."
```suggestion
                    "IAM password policy does not require at least one lowercase letter.
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_reuse_24/iam_password_policy_reuse_24.py
> +                    f"Password reuse prevention in password policy is equal to 24."
```suggestion
                    "IAM password policy reuse prevention is equal to 24."
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_reuse_24/iam_password_policy_reuse_24.py
> +                report.status_extended = f"Password reuse prevention in password policy is less than 24 or not set."
```suggestion
                report.status_extended = "IAM password policy reuse prevention is less than 24 or not set.""
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_reuse_24/iam_password_policy_reuse_24.py
> +            report.status_extended = f"Password policy cannot be found"
```suggestion
            report.status_extended = "There is no password policy."
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_reuse_24/iam_password_policy_reuse_24_test.py
> +        iam_client.update_account_password_policy(MinimumPasswordLength=20)
```suggestion
        iam_client.update_account_password_policy(PasswordReusePrevention=20)
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_symbol/iam_password_policy_symbol.metadata.json
> +      "Text": "Ensure \"Require at least one non-alphanumeric character\" is checked under \"Password Policy\"..",
```suggestion
      "Text": "Ensure \"Require at least one non-alphanumeric character\" is checked under \"Password Policy\".",
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_symbol/iam_password_policy_symbol.py
> +                    f"Password symbol option in password policy is set."
```suggestion
                    "IAM password policy requires at least one symbol."
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_symbol/iam_password_policy_symbol.py
> +                    f"Password symbol option in password policy is not set."
```suggestion
                    "IAM password policy does not require at least one symbol."
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_symbol/iam_password_policy_symbol.py
> +            report.status_extended = f"Password policy cannot be found"
```suggestion
            report.status_extended = "There is no password policy."
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_uppercase/iam_password_policy_uppercase.py
> +                    f"Password uppercase option in password policy is set."
```suggestion
                   "IAM password policy requires at least one uppercase letter."
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_uppercase/iam_password_policy_uppercase.py
> +                    f"Password uppercase option in password policy is not set."
```suggestion
                    "IAM password policy does not require at least one uppercase letter."
```

2022-10-18 07:48 UTC, jfagoagas commented on providers/aws/services/iam/iam_password_policy_uppercase/iam_password_policy_uppercase.py
> +            report.status_extended = f"Password policy cannot be found"
```suggestion
            report.status_extended = "There is no password policy."
```

2022-10-18 08:13 UTC, n4ch04 commented on providers/aws/services/iam/iam_password_policy_minimum_length_14/iam_password_policy_minimum_length_14.metadata.json
> +      "Text": "Ensure \"Minimum password length\" is checked under \"Password Policy\"..",
Done

2022-10-18 08:13 UTC, n4ch04 commented on providers/aws/services/iam/iam_password_policy_minimum_length_14/iam_password_policy_minimum_length_14.py
> +            # Check if symbol flag is set
DOne

2022-10-18 08:13 UTC, n4ch04 commented
All changed and included

2022-10-18 08:15 UTC, merged