Typo corrections in some files.
toniblyx/prowler pull request #1394
Opened 2022-10-09 00:52 UTC by olivier987654

Typos correction

### Context 

I actually went through the project and it's something that is really appealing to me. I'm actually a Cybersecurity student from Montreal and even if my abilities in coding right now are not very high, I still look for something to get my feets wet !

### Description

I corrected 3 typo errors, and 3 files were targeted as you will see underneath.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-18 10:37 UTC, jfagoagas commented
Hi @olivier987654, we can't merge this PR because the changes you propose breaks the documentation format we follow.

Please, do only spelling check and keep the format (using `*`, `tabs`, `_` and spaces as it is) 

Thanks!

2022-10-18 10:39 UTC, jfagoagas requested changes, later dismissed
Hi @olivier987654, we can't merge this PR because the changes you propose breaks the documentation format we follow.

Please, do only spelling check and keep the format (using *, tabs, _ and spaces as it is)

Thanks!

2022-10-24 10:58 UTC, toniblyx approved these changes

2022-10-24 10:58 UTC, toniblyx commented
Thanks for your suggestions!

2022-10-24 10:58 UTC, merged