feat(allowlist): add allowlist.yaml feature
toniblyx/prowler pull request #1395
Opened 2022-10-10 13:22 UTC by sergargar

### Context 

Add allowlist feature in Python.

### Description

- Allowlist yaml feature
- S3 feature
- DynamoDB feature with the following structure:
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/38561120/194876203-bf306527-c7b4-41cb-ad63-714f61340028.png">

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-20 15:57 UTC, jfagoagas requested changes
Great job @sergargar !! Please check my comments and then can merge 🥳

2022-10-20 15:57 UTC, jfagoagas commented on providers/aws/allowlist.yaml
> +            - "user-1"           # Will ignore user-2 in check iam_user_hardware_mfa_enabled
```suggestion
            - "user-1"           # Will ignore user-1 in check iam_user_hardware_mfa_enabled
```

2022-10-20 15:57 UTC, jfagoagas commented on providers/aws/allowlist.yaml
> +            - "user-2"           # Will ignore user-1 in check iam_user_hardware_mfa_enabled
```suggestion
            - "user-2"           # Will ignore user-2 in check iam_user_hardware_mfa_enabled
```

2022-10-20 15:57 UTC, jfagoagas commented on providers/aws/lib/allowlist/allowlist.py
> +        sys.exit()
```suggestion
def is_allowlisted(allowlist, audited_account, check, region, resource):
    try:
        if audited_account in allowlist["Accounts"]:
            if is_allowlisted_in_check(allowlist, audited_account, check, region, resource):
                return True
        # If there is a *, it affects to all accounts
        if "*" in allowlist["Accounts"]:
            audited_account = "*"
            if is_allowlisted_in_check(allowlist, audited_account, check, region, resource):
                return True
        return False
    except Exception as error:
        logger.critical(f"{error.__class__.__name__} -- {error}")
        sys.exit()
```

2022-10-20 15:57 UTC, jfagoagas commented on providers/aws/lib/allowlist/allowlist.py
> +                return True
```suggestion
def is_allowlisted_in_check(allowlist, audited_account, check, region, resource):
    # If there is a *, it affects to all checks
    if "*" in allowlist["Accounts"][account]["Checks"]:
        check = "*"
        if is_allowlisted_in_region(allowlist, audited_account, check, region, resource):
            return True
    # Check if there is the specific check
    if check in allowlist["Accounts"][account]["Checks"]:
        if is_allowlisted_in_region(allowlist, audited_account, check, region, resource):
            return True
    return False


def is_allowlisted_in_region(allowlist, audited_account, check, region, resource):
    # If there is a *, it affects to all regions
    if "*" in allowlist["Accounts"][audited_account]["Checks"][check]["Regions"]:
        for elem in allowlist["Accounts"][audited_account]["Checks"][check]["Resources"]:
            if re.search(elem, resource):
                return True
    # Check if there is the specific region
    if region in allowlist["Accounts"][audited_account]["Checks"][check]["Regions"]:
        for elem in allowlist["Accounts"][audited_account]["Checks"][check]["Resources"]:
            if re.search(elem, resource):
                return True
```

2022-10-20 15:57 UTC, jfagoagas commented on providers/aws/lib/allowlist/allowlist.py
> +        sys.exit()
Include the logger line trick

2022-10-20 15:57 UTC, jfagoagas commented on prowler
> +        default=allowlist_yaml,
```suggestion
        #default=allowlist_yaml,
```

2022-10-20 16:08 UTC, sergargar commented on providers/aws/lib/allowlist/allowlist.py
> +    if "*" in allowlist["Accounts"][account]["Checks"]:
```suggestion
    if "*" in allowlist["Accounts"][audited_account]["Checks"]:
```

2022-10-20 16:08 UTC, sergargar commented on providers/aws/lib/allowlist/allowlist.py
> +    if check in allowlist["Accounts"][account]["Checks"]:
```suggestion
    if check in allowlist["Accounts"][audited_account]["Checks"]:
```

2022-10-21 06:38 UTC, jfagoagas approved these changes
Good job @sergargar !!

2022-10-21 09:33 UTC, jfagoagas approved these changes

2022-10-21 09:33 UTC, merged