feat(apigateway_checks): service and checks for apigw v1 and v2
toniblyx/prowler pull request #1415
Opened 2022-10-18 14:14 UTC by sergargar

### Context 

Add checks, services and tests for ApiGateway version 1 & 2 since we need to migrate them to the new version 3.

### Description

Add checks, services and tests for ApiGateway version 1 & 2 

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-19 08:20 UTC, jfagoagas commented
Test

2022-10-19 14:06 UTC, n4ch04 requested changes, later dismissed

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigateway/apigateway_authorizers_enabled/apigateway_authorizers_enabled_test.py
> +            assert len(result) == 0
Add assertion to other fields of the `Check_Report` like `resource_id` or `status_extended`

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigateway/apigateway_authorizers_enabled/apigateway_authorizers_enabled_test.py
> +            assert result[0].status == "PASS"
Same here

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigateway/apigateway_authorizers_enabled/apigateway_authorizers_enabled_test.py
> +            assert result[0].status == "FAIL"
Same as above

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigateway/apigateway_authorizers_enabled/apigateway_authorizers_enabled_test.py
> +            assert len(result) == 0
Same as above

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigateway/apigateway_client_certificate_enabled/apigateway_client_certificate_enabled_test.py
> +            assert len(result) == 0
Same as other tests

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigateway/apigateway_client_certificate_enabled/apigateway_client_certificate_enabled_test.py
> +    # @mock_apigateway
Delete this comment if it is not needed

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigateway/apigateway_client_certificate_enabled/apigateway_client_certificate_enabled_test.py
> +            assert result[0].status == "FAIL"
Same as other tests

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigateway/apigateway_client_certificate_enabled/apigateway_client_certificate_enabled_test.py
> +            assert len(result) == 0
Same as other tests

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigateway/apigateway_endpoint_public/apigateway_endpoint_public_test.py
> +
Check all the assertions

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigateway/apigateway_endpoint_public/apigateway_endpoint_public_test.py
> +    def test_apigateway_one_prublic_rest_api(self):
```suggestion
    def test_apigateway_one_public_rest_api(self):
```

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigateway/apigateway_logging_enabled/apigateway_logging_enabled_test.py
> +
Check all the assertions

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigateway/apigateway_waf_acl_attached/apigateway_waf_acl_attached_test.py
> +
Check all the assertions

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigatewayv2/apigatewayv2_access_logging_enabled/apigatewayv2_access_logging_enabled_test.py
> +import botocore
Check all the assertions

2022-10-19 14:06 UTC, n4ch04 commented on providers/aws/services/apigatewayv2/apigatewayv2_authorizers_enabled/apigatewayv2_authorizers_enabled_test.py
> +import botocore
Check all the assertions

2022-10-20 15:09 UTC, sergargar commented on providers/aws/services/apigateway/apigateway_authorizers_enabled/apigateway_authorizers_enabled_test.py
> +            assert len(result) == 0
Done

2022-10-20 15:09 UTC, sergargar commented on providers/aws/services/apigateway/apigateway_authorizers_enabled/apigateway_authorizers_enabled_test.py
> +            assert result[0].status == "PASS"
Done

2022-10-20 15:09 UTC, sergargar commented on providers/aws/services/apigateway/apigateway_authorizers_enabled/apigateway_authorizers_enabled_test.py
> +            assert result[0].status == "FAIL"
Done

2022-10-20 15:09 UTC, sergargar commented on providers/aws/services/apigateway/apigateway_authorizers_enabled/apigateway_authorizers_enabled_test.py
> +            assert len(result) == 0
Done

2022-10-20 15:09 UTC, sergargar commented on providers/aws/services/apigateway/apigateway_client_certificate_enabled/apigateway_client_certificate_enabled_test.py
> +            assert len(result) == 0
Done

2022-10-20 15:09 UTC, sergargar commented on providers/aws/services/apigateway/apigateway_logging_enabled/apigateway_logging_enabled_test.py
> +
Done

2022-10-20 15:09 UTC, sergargar commented on providers/aws/services/apigateway/apigateway_waf_acl_attached/apigateway_waf_acl_attached_test.py
> +
Done

2022-10-20 15:09 UTC, sergargar commented on providers/aws/services/apigatewayv2/apigatewayv2_access_logging_enabled/apigatewayv2_access_logging_enabled_test.py
> +import botocore
Done

2022-10-20 15:09 UTC, sergargar commented on providers/aws/services/apigatewayv2/apigatewayv2_authorizers_enabled/apigatewayv2_authorizers_enabled_test.py
> +import botocore
Done

2022-10-31 12:34 UTC, jfagoagas commented on providers/aws/services/apigateway/apigateway_client_certificate_enabled/apigateway_client_certificate_enabled_test.py
> +            assert result[0].status == "FAIL"
Done

2022-10-31 12:34 UTC, jfagoagas commented on providers/aws/services/apigateway/apigateway_client_certificate_enabled/apigateway_client_certificate_enabled_test.py
> +    # @mock_apigateway
Done

2022-10-31 12:38 UTC, jfagoagas requested changes

2022-10-31 12:38 UTC, jfagoagas commented on providers/aws/services/apigateway/apigateway_client_certificate_enabled/apigateway_client_certificate_enabled_test.py
> +    # @mock_apigateway
Pending mocked test

2022-10-31 13:12 UTC, jfagoagas approved these changes
Let's go 🚀

2022-10-31 13:13 UTC, merged