Prwlr 1042 ecr service and checks
toniblyx/prowler pull request #1475
Opened 2022-11-14 16:53 UTC by n4ch04

### Context

It is needed to migrate ECR checks to prowler v3

### Description

Includes ECR checks and service 

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-15 15:52 UTC, sergargar requested changes
Great job 🔝 Please, check my comments.

2022-11-15 15:52 UTC, sergargar commented on providers/aws/services/ecr/ecr_repositories_not_publicly_accessible/ecr_repositories_not_publicly_accessible.metadata.json
> +        "Other": "",
```suggestion
        "Other": "https://docs.bridgecrew.io/docs/public_1-ecr-repositories-not-public#aws-console",
```

2022-11-15 15:52 UTC, sergargar commented on providers/aws/services/ecr/ecr_repositories_not_publicly_accessible/ecr_repositories_not_publicly_accessible.py
> +                        and statement["Principal"]["AWS"] == "*"
What about Principal:* ?

2022-11-15 15:52 UTC, sergargar commented on providers/aws/services/ecr/ecr_repositories_scan_images_on_push_enabled/ecr_repositories_scan_images_on_push_enabled.metadata.json
> +    "CheckType": ["Identify", "Vulnerability, patch, and version management"],
```suggestion
    "CheckType": ["Identify", "Vulnerability patch and version management"],
```

2022-11-15 15:52 UTC, MrCloudSec commented on providers/aws/services/ecr/ecr_repositories_scan_images_on_push_enabled/ecr_repositories_scan_images_on_push_enabled.metadata.json
> +        "CLI": "aws ecr create-repository --repository-name name --image-scanning-configuration scanOnPush=true--region us-east-2",
```suggestion
        "CLI": "aws ecr create-repository --repository-name <repo_name> --image-scanning-configuration scanOnPush=true--region <region_name>",
```

2022-11-17 18:25 UTC, sergargar commented on providers/aws/services/ecr/ecr_repositories_not_publicly_accessible/ecr_repositories_not_publicly_accessible.py
> +                        and statement["Principal"]["AWS"] == "*"
Solved

2022-11-17 18:36 UTC, sergargar approved these changes

2022-11-17 18:41 UTC, merged