feat(): ECS service and checks
toniblyx/prowler pull request #1476
Opened 2022-11-15 07:59 UTC by n4ch04

### Context 

It is needed to migrate ECS and its checks from version 2 to 3

### Description

ECS service and checks

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-15 09:10 UTC, jfagoagas requested changes, later dismissed
Good job, please check my comments to merge.

2022-11-15 09:10 UTC, jfagoagas commented on providers/aws/services/ecs/ecs_service.py
> +        logger.info("ECS listing task definitions...")
```suggestion
        logger.info("ECS - Listing Task Definitions...")
```

2022-11-15 09:10 UTC, jfagoagas commented on providers/aws/services/ecs/ecs_service.py
> +    def __describe_task_definition__(self):
```suggestion
    def __describe_task_definition__(self):
    logger.info("ECS - Describing Task Definitions...")
        try:
```

2022-11-15 09:10 UTC, jfagoagas commented on providers/aws/services/ecs/ecs_service.py
> +    def __describe_task_definition__(self):
Missing try-except clause

2022-11-15 09:10 UTC, jfagoagas commented on providers/aws/services/ecs/ecs_task_definitions_no_environment_secrets/ecs_task_definitions_no_environment_secrets.metadata.json
> +    "CheckTitle": "Check if there exists secrets in ECS task definitions environment variables",
```suggestion
    "CheckTitle": "Check if secrets exists in ECS task definitions environment variables",
```

2022-11-15 09:10 UTC, jfagoagas commented on providers/aws/services/ecs/ecs_task_definitions_no_environment_secrets/ecs_task_definitions_no_environment_secrets.metadata.json
> +    "Description": "Check if there exists secrets in ECS task definitions environment variables",
```suggestion
    "Description": "Check if secrets exists in ECS task definitions environment variables",
```

2022-11-15 09:10 UTC, jfagoagas commented on providers/aws/services/ecs/ecs_task_definitions_no_environment_secrets/ecs_task_definitions_no_environment_secrets.metadata.json
> +        "CLI": "aws ecs describe-task-definition --region <REGION> --task-definition <TASK_DEFINITION_NAME> --query taskDefinition.containerDefinitions[*].environment",
```suggestion
        "CLI": "",
```

2022-11-15 09:10 UTC, jfagoagas commented on providers/aws/services/ecs/ecs_task_definitions_no_environment_secrets/ecs_task_definitions_no_environment_secrets.py
> +                temp_env_data_file.write(bytes(env_data, encoding="raw_unicode_escape"))
Check this, you don't need the `b64` operations, use the `dump_env_vars` values as plain text.

2022-11-15 09:10 UTC, jfagoagas commented on providers/aws/services/ecs/ecs_task_definitions_no_environment_secrets/ecs_task_definitions_no_environment_secrets_test.py
> +class Test_ecs_task_definitions_no_environment_secrets:
I would include a test case checking no task definitions.

2022-11-17 21:24 UTC, sergargar commented on providers/aws/services/ecs/ecs_task_definitions_no_environment_secrets/ecs_task_definitions_no_environment_secrets_test.py
> +class Test_ecs_task_definitions_no_environment_secrets:
Done

2022-11-17 21:24 UTC, sergargar commented on providers/aws/services/ecs/ecs_service.py
> +    def __describe_task_definition__(self):
Done

2022-11-17 21:27 UTC, sergargar commented on providers/aws/services/ecs/ecs_task_definitions_no_environment_secrets/ecs_task_definitions_no_environment_secrets.py
> +                temp_env_data_file.write(bytes(env_data, encoding="raw_unicode_escape"))
Done

2022-11-17 21:47 UTC, MrCloudSec approved these changes

2022-11-17 21:54 UTC, merged