fix(compliance): Set Version as optional and fix list
toniblyx/prowler pull request #1899
Opened 2023-02-14 08:15 UTC by jfagoagas

### Context

Version was not set as optional and also the `--list-compliance-requirements` is broken.

### Description

- Set Version as optional
- Include Framework and Provider validator
- Remove code to fix the `--list-compliance-requirements`

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-14 11:09 UTC, toniblyx requested changes
Despite listing seems to work fine now. However when executing more than one framework like in:
```
./prowler.py aws --compliance aws_audit_manager_control_tower_guardrails_aws ffiec_aws gdpr_aws aws_foundational_security_best_practices_aws
```
Only the first one is shown, in the example above only `Detailed results of AWS_AUDIT_MANAGER_CONTROL_TOWER_GUARDRAILS_AWS are in:` however all files are generated properly. So the results  of file locations are not properly shown.

2023-02-14 11:22 UTC, jfagoagas commented
> Despite listing seems to work fine now. However when executing more than one framework like in:
> 
> ```
> ./prowler.py aws --compliance aws_audit_manager_control_tower_guardrails_aws ffiec_aws gdpr_aws aws_foundational_security_best_practices_aws
> ```
> 
> Only the first one is shown, in the example above only `Detailed results of AWS_AUDIT_MANAGER_CONTROL_TOWER_GUARDRAILS_AWS are in:` however all files are generated properly. So the results of file locations are not properly shown.


@sergargar could you please take a look at this lines? https://github.com/prowler-cloud/prowler/blob/master/prowler/lib/outputs/compliance.py#L361-L369

We have to loop through every framework to print its output location.

2023-02-15 08:53 UTC, MrCloudSec commented
> Despite listing seems to work fine now. However when executing more than one framework like in:
> 
> ```
> ./prowler.py aws --compliance aws_audit_manager_control_tower_guardrails_aws ffiec_aws gdpr_aws aws_foundational_security_best_practices_aws
> ```
> 
> Only the first one is shown, in the example above only `Detailed results of AWS_AUDIT_MANAGER_CONTROL_TOWER_GUARDRAILS_AWS are in:` however all files are generated properly. So the results of file locations are not properly shown.

Good catch! This is fix now.

2023-02-16 11:47 UTC, toniblyx approved these changes

2023-02-16 11:47 UTC, merged