chore(poetry): make python-poetry as packaging and dependency manager
toniblyx/prowler pull request #1935
Opened 2023-02-20 16:17 UTC by sergargar

### Description

Make python-poetry as packaging and dependency manager.
Now, provider dependencies are optional for pip installation:
```bash
pip install 'prowler[all]'
pip install 'prowler[aws]'
pip install 'prowler[azure]'
```

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-21 15:34 UTC, sergargar commented on .github/workflows/pypi-release.yml
>            pip install build toml --upgrade
```suggestion
          pip install poetry
```

2023-02-21 15:35 UTC, sergargar commented on .github/workflows/build-lint-push-containers.yml
> +          python -m pip install --upgrade pip
```suggestion
          python -m pip install --upgrade pip
          pip install poetry
```

2023-02-21 15:36 UTC, sergargar commented on README.md
> +pip install 'prowler[aws,azure,all]'
```suggestion
pip install prowler
```

2023-02-21 15:37 UTC, sergargar commented on docs/index.md
> +    pip install 'prowler[aws,azure,all]'
```suggestion
    pip install prowler
```

2023-02-23 09:56 UTC, jfagoagas requested changes

2023-02-23 09:56 UTC, jfagoagas commented on .github/workflows/build-lint-push-containers.yml
> +      - name: Build package
```suggestion
      - name: Update Prowler version
```

2023-02-23 09:56 UTC, jfagoagas commented on .github/workflows/pypi-release.yml
> +          git commit -m "Release version" --no-verify
```suggestion
          git commit -m "release: ${{ env.GITHUB_BRANCH }}" --no-verify
```

2023-02-23 09:56 UTC, jfagoagas commented on .github/workflows/pypi-release.yml
> +        uses: peter-evans/create-pull-request@v4
You have to set the `base` branch because the PR goes to `master` not to the release branch.

2023-02-23 09:56 UTC, jfagoagas commented on .github/workflows/pypi-release.yml
> +          title: "chore(release): update prowler_version config variable."
```suggestion
          title: "chore(release): update prowler_version config variable to ${{ env.GITHUB_BRANCH }}"
```

2023-02-23 09:56 UTC, jfagoagas commented on .github/workflows/pypi-release.yml
> +            This PR updates prowler_version config variable.
```suggestion
            This PR updates prowler_version config variable to the ${{ env.GITHUB_BRANCH }}.
```

2023-02-23 09:57 UTC, sergargar commented on .github/workflows/pypi-release.yml
> +          title: "chore(release): update prowler_version config variable."
Done

2023-02-23 09:57 UTC, sergargar commented on .github/workflows/pypi-release.yml
> +            This PR updates prowler_version config variable.
Done

2023-02-23 09:58 UTC, sergargar commented on .github/workflows/pypi-release.yml
> +        uses: peter-evans/create-pull-request@v4
Done

2023-02-23 09:58 UTC, sergargar commented on .github/workflows/pypi-release.yml
> +          git commit -m "Release version" --no-verify
Done

2023-02-23 10:00 UTC, n4ch04 approved these changes, later dismissed

2023-02-23 10:03 UTC, sergargar commented on .github/workflows/pypi-release.yml
> +          git add .
```suggestion
          git add prowler/config/config.py pyproject.toml
```

2023-02-23 10:06 UTC, jfagoagas approved these changes, later dismissed
<img src="https://media4.giphy.com/media/sbXpFKDoK7ObhrasIv/giphy.gif"/>

2023-02-23 10:50 UTC, jfagoagas approved these changes
Let's go!

2023-02-23 10:50 UTC, merged