feat(rds_instance_transport_encrypted): add new check
toniblyx/prowler pull request #1963
Opened 2023-02-23 15:35 UTC by sergargar

### Description

Add new check called `rds_instance_transport_encrypted`

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-28 13:57 UTC, sergargar reviewed
Thanks to @Fennerr for the idea!

2023-02-28 13:57 UTC, sergargar commented on prowler/providers/aws/services/rds/rds_instance_transport_encrypted/rds_instance_transport_encrypted.py
> +        supported_engines = ["sqlserver-ex", "postgres"]
```suggestion
        supported_engines = ["sqlserver", "postgres"]
```

2023-02-28 13:57 UTC, sergargar commented on prowler/providers/aws/services/rds/rds_instance_transport_encrypted/rds_instance_transport_encrypted.py
> +            if db_instance.engine in supported_engines:
```suggestion
            if any(engine in db_instance.engine for engine in supported_engines):
```

2023-02-28 14:06 UTC, sergargar commented on prowler/providers/aws/services/rds/rds_instance_transport_encrypted/rds_instance_transport_encrypted.metadata.json
> +      "Url": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL.Concepts.General.SSL.html"
```suggestion
      "Url": "https://aws.amazon.com/premiumsupport/knowledge-center/rds-connect-ssl-connection/"
```

2023-02-28 14:06 UTC, sergargar commented on prowler/providers/aws/services/rds/rds_instance_transport_encrypted/rds_instance_transport_encrypted.metadata.json
> +  "RelatedUrl": "https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL.Concepts.General.SSL.html",
```suggestion
  "RelatedUrl": "https://aws.amazon.com/premiumsupport/knowledge-center/rds-connect-ssl-connection/",
```

2023-02-28 14:06 UTC, sergargar commented on prowler/providers/aws/services/rds/rds_instance_transport_encrypted/rds_instance_transport_encrypted.metadata.json
> +  },
```suggestion
```

2023-03-02 13:52 UTC, toniblyx requested changes

2023-03-02 13:52 UTC, toniblyx commented on prowler/providers/aws/services/rds/rds_instance_transport_encrypted/rds_instance_transport_encrypted.metadata.json
> +  "Categories": [],
```suggestion
  "Categories": [ "encryption" ],
```

2023-03-02 13:52 UTC, toniblyx commented on prowler/providers/aws/services/rds/rds_instance_transport_encrypted/rds_instance_transport_encrypted.metadata.json
> +  "CheckTitle": "Check if RDS instances client connections are encrypted.",
```suggestion
  "CheckTitle": "Check if RDS instances client connections are encrypted (Postgresql and MS SQL Server).",
```

2023-03-02 15:06 UTC, Fennerr commented
Just moving across the info from the slack chat I had with Sergio to here:

For Oracle databases the rds client also needs to retrieve the option groups, and then check for the SQLNET.SSL_VERSION option to that group. https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.Oracle.Options.SSL.html#Appendix.Oracle.Options.SSL.OptionGroup
The following values are allowed for this option setting:

    "1.0" - Clients can connect to the DB instance using TLS 1.0 only.
    "1.2" - Clients can connect to the DB instance using TLS 1.2 only.
    "1.2 or 1.0" - Clients can connect to the DB instance using either TLS 1.2 or 1.0.

The check can also check if it is set to use TLS 1.0
> For existing Oracle SSL options, SQLNET.SSL_VERSION is set to "1.0" automatically. You can change the setting, if necessary.

I can add this to the current check, or it can be a separate check

2023-03-06 11:07 UTC, sergargar commented on prowler/providers/aws/services/rds/rds_instance_transport_encrypted/rds_instance_transport_encrypted.metadata.json
> +  "Description": "Check if RDS instances client connections are encrypted.",
```suggestion
  "Description": "Check if RDS instances client connections are encrypted (Microsoft SQL Server and PostgreSQL).",
```

2023-03-06 11:09 UTC, sergargar commented
> Just moving across the info from the slack chat I had with Sergio to here:
> 
> For Oracle databases the rds client also needs to retrieve the option groups, and then check for the SQLNET.SSL_VERSION option to that group. https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Appendix.Oracle.Options.SSL.html#Appendix.Oracle.Options.SSL.OptionGroup The following values are allowed for this option setting:
> 
> ```
> "1.0" - Clients can connect to the DB instance using TLS 1.0 only.
> "1.2" - Clients can connect to the DB instance using TLS 1.2 only.
> "1.2 or 1.0" - Clients can connect to the DB instance using either TLS 1.2 or 1.0.
> ```
> 
> The check can also check if it is set to use TLS 1.0
> 
> > For existing Oracle SSL options, SQLNET.SSL_VERSION is set to "1.0" automatically. You can change the setting, if necessary.
> 
> I can add this to the current check, or it can be a separate check

@Fennerr, this is a great idea, but as we have decided to leave this check for Microsoft SQL Server and PostgreSQL instances, we would prefer the Oracle logic to be in another check. It would be awesome if you can do it, we have include it in our roadmap anyway.

2023-03-06 12:16 UTC, toniblyx approved these changes

2023-03-06 12:18 UTC, merged