CloudWatch logs secrets check
toniblyx/prowler pull request #1980
Opened 2023-02-26 19:48 UTC by Fennerr

### Context

Added a check to look for secrets in CloudWatch logs

### Description

Altered the CloudWatch Logs class to get log events for each log group. There are 2 parameters that determine the number of events that are collected. 
* number_of_log_streams_to_retrieve determines the number of log streams per log group to get. The latest log streams are retrieved
* events_per_log_stream_threshold determines the threshold for the number of events before it stops collecting more events. It will retrieve at most events_per_log_stream_threshold + events_per_log_stream_threshold-1 events. Could alter this to retrieve exactly events_per_log_stream_threshold, but it didn't seem to make a performance difference. Can discuss this further over slack if you want.
I think that these parameters should be configured in the config file.

The check will output all the events into a temp file, and run detect-secrets on them. If a secret is detected, it will then look to see if it can give more specific information on what lines the secrets were detected on for that event. I do this by using json.loads on the event message, and then doing a json.dumps with the indent parameter set to 2. If there are multiple lines after this, then the event is run through detect-secrets again to determine which lines of the secrets are being flagged on. I found this useful for logs being generated for the aws-controltower/CloudTrailLogs log group which outputs logs as json messages. 

The convert_to_cloudwatch_timestamp_format function in the check could move to the cloudwatch_service file, and the detect_secrets_scan function and potentially the SecretsDict could move to the utils file.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-26 19:49 UTC, Fennerr commented
I am a git noob, and I see that the commits that I made to the other branch are also in this branch.. Will look into this

2023-02-27 08:59 UTC, jfagoagas requested changes

2023-02-27 08:59 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_no_secerts_in_logs/cloudwatch_no_secerts_in_logs.metadata.json
> +  "CheckID": "cloudwatch_no_secerts_in_logs",
```suggestion
  "CheckID": "cloudwatch_no_secrets_in_logs",
```

2023-02-27 10:06 UTC, sergargar commented
> I am a git noob, and I see that the commits that I made to the other branch are also in this branch.. Will look into this

I solved it, no worries!

2023-02-27 10:14 UTC, jfagoagas requested changes

2023-02-27 10:14 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_service.py
> +        if "cloudwatch_no_secerts_in_logs" in audit_info.audit_metadata.expected_checks:
```suggestion
        if "cloudwatch_no_secrets_in_logs" in audit_info.audit_metadata.expected_checks:
```

2023-02-27 12:19 UTC, sergargar commented
@Fennerr I simplified the service calls by only using the `filter_log_events ` call and setting a limit of the amount of events per log group.

2023-02-27 16:01 UTC, sergargar submitted a review, later dismissed
Thank you for this amazing contribution @Fennerr 🚀

2023-02-28 06:50 UTC, JeffreySouza commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_group_no_secrets_in_logs/cloudwatch_log_group_no_secrets_in_logs.py
> +                                ]
Nit:
```suggestion
                                for secret in event_detect_secrets_output:
                                    log_stream_secrets[cloudwatch_timestamp].add_secret(
                                        secret["line_number"], secret["type"]
                                    )
```

2023-03-06 11:12 UTC, MrCloudSec approved these changes

2023-03-06 11:16 UTC, jfagoagas approved these changes
Go!

2023-03-06 11:16 UTC, merged