chore(version): check latest version
toniblyx/prowler pull request #2106
Opened 2023-03-17 13:13 UTC by sergargar

### Description

Check latest version of Prowler in `--version` flag:
`Prowler 3.3.0 (it is the latest version, yay!)`
`Prowler 3.2.0 (latest is 3.3.0, upgrade for the latest features)`

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-17 13:45 UTC, sergargar commented on prowler/__main__.py
> +from prowler.config.config import check_current_version
```suggestion
```

2023-03-17 13:46 UTC, sergargar commented on prowler/__main__.py
> +
```suggestion
```

2023-03-21 07:20 UTC, jfagoagas requested changes

2023-03-21 07:20 UTC, jfagoagas commented on prowler/config/config.py
> +        return ""
Maybe we need to log some error here and then return, like:
```suggestion
       log.error()
   finally:
       return
```

2023-03-21 10:16 UTC, jfagoagas approved these changes

2023-03-21 10:16 UTC, merged