feat(defender service): retrieving key dicts with get
toniblyx/prowler pull request #2129
Opened 2023-03-24 10:47 UTC by n4ch04

### Context

It seems to be some problems with certain Azure defender service configuration, some dict keys were not present

### Description

Fixes `defender` checks including `get` method for dict keys

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-24 12:40 UTC, sergargar requested changes

2023-03-24 12:40 UTC, sergargar commented on prowler/providers/azure/services/defender/defender_ensure_defender_for_databases_is_on/defender_ensure_defender_for_databases_is_on.py
> +                and "CosmosDbs" in pricings
I would check one by one.

2023-03-27 11:49 UTC, n4ch04 commented on prowler/providers/azure/services/defender/defender_ensure_defender_for_databases_is_on/defender_ensure_defender_for_databases_is_on.py
> +                and "CosmosDbs" in pricings
It needs the four pricings to be enabled, so there is no point in checking it one by one

2023-03-27 11:51 UTC, sergargar submitted a review, later dismissed

2023-03-27 12:21 UTC, sergargar submitted a review, later dismissed

2023-03-27 15:01 UTC, sergargar approved these changes, later dismissed
🔝 🔝 🔝

2023-03-27 15:04 UTC, sergargar approved these changes
🔝 🔝

2023-03-27 15:13 UTC, merged