feat(html): add html to Azure and GCP
toniblyx/prowler pull request #2181
Opened 2023-04-10 09:35 UTC by sergargar

### Description

Add HTML output to Azure and GCP providers.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-13 10:53 UTC, toniblyx requested changes
Can you attach sample screenshots of both GCP and Azure html reports?

2023-04-13 11:43 UTC, sergargar commented
> Can you attach sample screenshots of both GCP and Azure html reports?

Done

2023-04-14 05:51 UTC, jfagoagas requested changes
Please, rebase this branch with `master` to get the tests fixes.

2023-04-14 10:48 UTC, toniblyx approved these changes, later dismissed

2023-04-14 11:05 UTC, jfagoagas requested changes

2023-04-14 11:05 UTC, jfagoagas commented on prowler/lib/outputs/html.py
> +        sys.exit(1)
I'm not sure about this change, what are we doing for the other output formats?

2023-04-14 11:05 UTC, jfagoagas commented on prowler/providers/common/audit_info.py
> +            audit_info.profile = (
Why are you changing the input `audit_info` instead of using a new variable? Just curious.

2023-04-14 11:05 UTC, jfagoagas commented on prowler/providers/common/outputs.py
I like this one!

2023-04-14 11:14 UTC, sergargar commented on prowler/providers/common/audit_info.py
> +            audit_info.profile = (
to store it and use it in the future

2023-04-14 11:16 UTC, jfagoagas commented on prowler/providers/common/audit_info.py
> +            audit_info.profile = (
But you are not returning it in this function, I'm not happy with the idea of modifying that object to use it in the future.

2023-04-14 11:19 UTC, sergargar commented on prowler/lib/outputs/html.py
> +        sys.exit(1)
We are using the critical error too, if a file cannot be created is a sys exit.

2023-04-14 11:24 UTC, sergargar commented on prowler/providers/common/audit_info.py
> +            audit_info.profile = (
How we should do it?

2023-04-14 11:25 UTC, jfagoagas commented on prowler/providers/common/audit_info.py
> +            audit_info.profile = (
What is the problem leaving it as it was?

2023-04-14 11:25 UTC, sergargar commented on prowler/providers/common/audit_info.py
> +            audit_info.profile = (
Because the profile is need it in the HTML

2023-04-14 11:38 UTC, sergargar commented on prowler/providers/common/audit_info.py
> +            audit_info.profile = (
I can do the same condition when doing the html

2023-04-14 12:40 UTC, jfagoagas commented on prowler/providers/common/audit_info.py
> +            audit_info.profile = (
I still don't understand it, the `profile` used within `print_gcp_credentials` is never returned so the `profile` used in the HTML should be another object with the same name. Am I missing something?

2023-04-17 10:50 UTC, sergargar commented on prowler/providers/common/audit_info.py
> +            audit_info.profile = (
Done!

2023-04-18 14:13 UTC, toniblyx approved these changes

2023-04-18 14:13 UTC, jfagoagas approved these changes
🚀

2023-04-18 14:13 UTC, merged