feat(checks): New iam_securityaudit_role_created
toniblyx/prowler pull request #2182
Opened 2023-04-10 14:30 UTC by gabrielsoltz

### Context

This is a new IAM check: `iam_securityaudit_role_created`
Description: Ensure a Security Audit role has been created to conduct security audits

### Description

Creating an IAM user with a security audit role provides a clear separation of duties between the security team and other teams within the organization. This helps to ensure that security-related activities are performed by authorized individuals with the appropriate expertise and access permissions.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-10 14:32 UTC, sergargar reviewed
Awesome job! 
I would change the check name to iam_role_securityaudit_created so we follow the pattern service_subservice_etc...

2023-04-10 14:35 UTC, gabrielsoltz commented
@sergargar i used this as reference: https://github.com/prowler-cloud/prowler/tree/master/prowler/providers/aws/services/iam/iam_support_role_created

2023-04-11 05:53 UTC, jfagoagas requested changes
Good job @gabrielsoltz, could you please check my comments then it'll be ready to merge 🚀

2023-04-11 05:53 UTC, jfagoagas commented on prowler/providers/aws/services/iam/iam_service.py
> +
Could you merge this function with the `__get_entities_attached_to_support_roles__` and pass the Role ARN as an argument?

Maybe you don't need neither of that and only use the `list_entities_for_policy`

2023-04-11 05:53 UTC, jfagoagas commented on tests/providers/aws/services/iam/iam_securityaudit_role_created/iam_securityaudit_role_created_test.py
> +                assert result[0].status == "PASS"
Can you assert also the finding region?

2023-04-11 05:53 UTC, jfagoagas commented on tests/providers/aws/services/iam/iam_securityaudit_role_created/iam_securityaudit_role_created_test.py
> +                assert result[0].resource_id == "SecurityAudit"
Can you assert also the finding region?

2023-04-11 12:04 UTC, gabrielsoltz commented on prowler/providers/aws/services/iam/iam_service.py
> +
I merged both functions into only one with an argument, I also took the freedom to rename the lists we are using for these checks, as the names were incorrect... These are entities (roles) for a policy, not for a role, the role is the entity.

2023-04-11 12:11 UTC, jfagoagas approved these changes
🚀

2023-04-11 12:15 UTC, merged