feat(check): New cloudtrail_bucket_requires_mfa_delete
toniblyx/prowler pull request #2194
Opened 2023-04-11 21:57 UTC by gabrielsoltz

### Context

New CloudTrail Check: `cloudtrail_bucket_requires_mfa_delete`

If the S3 bucket CloudTrail bucket does not require MFA, it can be deleted by an attacker.

Fixed the following failures in test:
- `AWS_ACCOUNT` must be a string.
- `Test_cloudtrail_logs_s3_bucket_is_not_publicly_accessible.test_trail_bucket_no_acl` was importing a bad S3 client from another test.
- Mock the `current_audit_info` object in all CloudTrail tests.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-12 08:56 UTC, jfagoagas requested changes
It is perfect @gabrielsoltz, just one comment about one test scenario and then it'll be ready to merge!

Thanks!

2023-04-12 08:56 UTC, jfagoagas commented on tests/providers/aws/services/cloudtrail/cloudtrail_bucket_requires_mfa_delete/cloudtrail_bucket_requires_mfa_delete_test.py
Could you include a test for the scenario where the trail bucket is cross-account?

2023-04-12 09:58 UTC, gabrielsoltz commented on tests/providers/aws/services/cloudtrail/cloudtrail_bucket_requires_mfa_delete/cloudtrail_bucket_requires_mfa_delete_test.py
i added two more ;)

2023-04-12 10:50 UTC, jfagoagas submitted a review, later dismissed
👏 👏 👏 👏 👏 

It's approved but I have to check what's happening with the test.

2023-04-12 10:51 UTC, jfagoagas commented
No merge label added until we fix the failing tests.

2023-04-13 12:18 UTC, jfagoagas approved these changes
🚀 🚀 🚀 🚀

2023-04-13 12:18 UTC, merged