feat(check): New Check and Service: resourceexplorer2_indexes_found
toniblyx/prowler pull request #2196
Opened 2023-04-12 05:40 UTC by gabrielsoltz

### Context

Nex Service: resource-explorer-2
New Check: resourceexplorer2_indexes_found

Resource Explorer Indexes Found: Not having Resource Explorer indexes can result in increased complexity and overhead in managing your resources, as well as increased risk of security and compliance issues.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-13 13:39 UTC, jfagoagas requested changes

2023-04-13 13:39 UTC, jfagoagas commented on prowler/providers/aws/services/resourceexplorer2/resourceexplorer2_service.py
> +        self.service = "resource-explorer-2"
```suggestion
        self.service = "resourceexplorer2"
```

2023-04-14 08:03 UTC, sergargar approved these changes, later dismissed

2023-04-14 08:03 UTC, sergargar commented on prowler/providers/aws/services/resourceexplorer2/resourceexplorer2_service.py
> +                        print(self.indexes)
```suggestion
```

2023-04-14 08:18 UTC, sergargar approved these changes
Awesome job!

2023-04-14 08:18 UTC, merged