feat(ssmincidents): New Service and Checks
toniblyx/prowler pull request #2219
Opened 2023-04-16 03:30 UTC by gabrielsoltz

### Context

New Service `ssmincidents` and check `ssmincidents_enabled_with_plans`:  Ensure SSM Incidents is enabled with response plans.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-17 09:11 UTC, jfagoagas requested changes
Pretty good 👍 

Please check my comments to merge this PR, thanks!

2023-04-17 09:11 UTC, jfagoagas commented on prowler/providers/aws/services/ssmincidents/ssmincidents_enabled_with_plans/ssmincidents_enabled_with_plans.py
You are only checking the first element of the `replication_sets`, what happens if the second element is active?

2023-04-17 09:11 UTC, jfagoagas commented on prowler/providers/aws/services/ssmincidents/ssmincidents_service.py
> +                        break
Why this `break` here?

2023-04-17 09:11 UTC, jfagoagas commented on prowler/providers/aws/services/ssmincidents/ssmincidents_service.py
> +                        # The ARN is listed in all regions, but it's only one uniq replication set
Are we calling this function for each region?

2023-04-17 09:11 UTC, jfagoagas commented on prowler/providers/aws/services/ssmincidents/ssmincidents_enabled_with_plans/ssmincidents_enabled_with_plans.py
> +class ssmincidents_enabled_with_plans(Check):
What is the relation between`ssmincidents_enabled_with_plans` enabled and the SSM replication sets? Just curious.

2023-04-17 09:11 UTC, jfagoagas commented on tests/providers/aws/services/ssmincidents/ssmincidents_service_test.py
> +                "createdBy": "thegaby",
```suggestion
                "createdBy": "Prowler",
```

2023-04-17 18:02 UTC, gabrielsoltz commented on prowler/providers/aws/services/ssmincidents/ssmincidents_enabled_with_plans/ssmincidents_enabled_with_plans.py
Answering here for both comments:

This is a weird service: I found that `ReplicationSets` are always deployed across all regions (no matter which region you enable the service). It's kinda Global service, but not, it's regional but it replicate to all other regions ALWAYS. The ARN is the same for every region, that's why i only save one in the service: https://github.com/gabrielsoltz/prowler/blob/ssmincidents/prowler/providers/aws/services/ssmincidents/ssmincidents_service.py#L57

Now after seeing your comment, maybe could be better to change https://github.com/gabrielsoltz/prowler/blob/ssmincidents/prowler/providers/aws/services/ssmincidents/ssmincidents_service.py#L57 this and don't loop across them and only save the element 0, but i wanted to be consistent with other checks. That's why I'm breaking the loop if i find one, that already means all the other ones are present (that's how a replication set work, still, very confusing.)

2023-04-17 18:02 UTC, gabrielsoltz commented on prowler/providers/aws/services/ssmincidents/ssmincidents_service.py
> +                        break
Answered in the other comment.

2023-04-17 18:05 UTC, gabrielsoltz commented on prowler/providers/aws/services/ssmincidents/ssmincidents_service.py
> +                        # The ARN is listed in all regions, but it's only one uniq replication set
Yes, this is not a global service, it's regional, the difference is this `ReplicationSets` that is always replicated across regions and share the same ARN.

2023-04-17 18:07 UTC, gabrielsoltz commented on prowler/providers/aws/services/ssmincidents/ssmincidents_enabled_with_plans/ssmincidents_enabled_with_plans.py
> +class ssmincidents_enabled_with_plans(Check):
For enabling ssm incidents, the first step is creating replication sets. No replications sets means service is disabled. Not sure if i answered your questions. 
Plans is on top of that, you can enable ssm incidents with or without plans. Here we are checking boths. 
Without plans the service is doing basically nothing.

2023-04-18 05:58 UTC, jfagoagas commented on prowler/providers/aws/services/ssmincidents/ssmincidents_enabled_with_plans/ssmincidents_enabled_with_plans.py
It's weird also another issue I saw is that you are executing the `break` but there are more for loops. Maybe it's better to talk about this later today, are you available?

2023-04-18 05:58 UTC, jfagoagas commented on prowler/providers/aws/services/ssmincidents/ssmincidents_enabled_with_plans/ssmincidents_enabled_with_plans.py
> +class ssmincidents_enabled_with_plans(Check):
Cool, understood!

2023-04-19 10:20 UTC, jfagoagas approved these changes

2023-04-19 10:26 UTC, merged