feat(inspector2): New Service and Check
toniblyx/prowler pull request #2250
Opened 2023-04-20 23:03 UTC by gabrielsoltz

### Context

Adding new Service `inspector2` and Check: `inspector2_findings_exist`: Check if Inspector2 findings exist

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-21 06:24 UTC, jfagoagas requested changes
Good job @gabrielsoltz !! Please check my comments to merge this PR.

2023-04-21 06:24 UTC, jfagoagas commented on prowler/providers/aws/services/inspector2/inspector2_service.py
Can we retrieve tags for this service?

2023-04-21 06:24 UTC, jfagoagas commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +                                title=finding["title"],
Please use the `dict.get()` notation here with default values not to raise `KeyErrors`. Thanks!

2023-04-21 06:24 UTC, jfagoagas commented on prowler/providers/aws/services/inspector2/inspector2_findings_exist/inspector2_findings_exist.metadata.json
> +  "CheckID": "inspector2_findings_exist",
What about `inspector2_enabled`? 

Does this service have statuses?

2023-04-21 06:24 UTC, jfagoagas commented on prowler/providers/aws/services/inspector2/inspector2_findings_exist/inspector2_findings_exist.metadata.json
> +      "Url": ""
```suggestion
      "Url": "https://docs.aws.amazon.com/inspector/latest/user/what-is-inspector.html"
```

2023-04-21 06:24 UTC, jfagoagas commented on prowler/providers/aws/services/inspector2/inspector2_findings_exist/inspector2_findings_exist.py
> +        report.region = inspector2_client.region
Is this a global service?

If not please use one of the findings region instead of the one we have as backup.

2023-04-21 06:24 UTC, jfagoagas commented on prowler/providers/aws/services/inspector2/inspector2_findings_exist/inspector2_findings_exist.py
> +        report.resource_id = "Inspector2"
Please, set the resource ARN as empty here.

2023-04-21 06:24 UTC, jfagoagas commented on tests/providers/aws/services/inspector2/inspector2_findings_exist/inspector2_findings_exist_test.py
> +            assert result[0].resource_arn == ""
Could you please assert the `region` and tags? Thanks!

2023-04-21 06:24 UTC, jfagoagas commented on tests/providers/aws/services/inspector2/inspector2_findings_exist/inspector2_findings_exist_test.py
> +            assert result[0].resource_arn == ""
Could you please assert the `region` and tags? Thanks!

2023-04-21 06:24 UTC, jfagoagas commented on tests/providers/aws/services/inspector2/inspector2_service_test.py
> +    def test__list_findings__(self):
Please, assert the `InspectorFinding` attributes when listing:
```
    arn: str
    region: str
    severity: str
    status: str
    title: str
```

2023-04-21 09:02 UTC, gabrielsoltz commented on prowler/providers/aws/services/inspector2/inspector2_service.py
we are only fetching findings and they don't provide tags

2023-04-21 09:02 UTC, gabrielsoltz commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +                                title=finding["title"],
Wops, fixed

2023-04-21 09:03 UTC, gabrielsoltz commented on prowler/providers/aws/services/inspector2/inspector2_findings_exist/inspector2_findings_exist.metadata.json
> +  "CheckID": "inspector2_findings_exist",
no, it does not, that's why we check if findings > 0 to see if the service is in-use

2023-04-21 09:09 UTC, gabrielsoltz commented on prowler/providers/aws/services/inspector2/inspector2_findings_exist/inspector2_findings_exist.py
> +        report.region = inspector2_client.region
added findings region when is >0

2023-04-21 09:10 UTC, gabrielsoltz commented on prowler/providers/aws/services/inspector2/inspector2_findings_exist/inspector2_findings_exist.py
> +        report.resource_id = "Inspector2"
fixed

2023-04-21 09:10 UTC, gabrielsoltz commented on tests/providers/aws/services/inspector2/inspector2_findings_exist/inspector2_findings_exist_test.py
> +            assert result[0].resource_arn == ""
✅

2023-04-21 09:10 UTC, gabrielsoltz commented on tests/providers/aws/services/inspector2/inspector2_findings_exist/inspector2_findings_exist_test.py
> +            assert result[0].resource_arn == ""
✅

2023-04-21 09:17 UTC, gabrielsoltz commented on tests/providers/aws/services/inspector2/inspector2_service_test.py
> +    def test__list_findings__(self):
fixed

2023-04-21 10:12 UTC, jfagoagas commented on prowler/providers/aws/services/inspector2/inspector2_service.py
Perfect then.

2023-04-21 10:12 UTC, jfagoagas commented on prowler/providers/aws/services/inspector2/inspector2_findings_exist/inspector2_findings_exist.metadata.json
> +  "CheckID": "inspector2_findings_exist",
Cool.

2023-04-21 10:15 UTC, jfagoagas submitted a review, later dismissed
Awesome!

2023-04-21 10:20 UTC, sergargar commented
@gabrielsoltz is it possible to check if Inspector is enabled?

2023-04-21 10:36 UTC, sergargar requested changes
How about doing the following cases:
1. FAIL if Inspector is disabled
2. FAIL if Inspector is enabled but with active findings
3. PASS if Inspector is enabled without findings

2023-04-24 06:46 UTC, jfagoagas requested changes

2023-04-24 06:46 UTC, jfagoagas commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +                    regional_client.get_configuration()
Can you retrieve something from this call?

2023-04-24 06:46 UTC, jfagoagas commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +                    if error.response["Error"]["Code"] == "ResourceNotFoundException":
Is this a global service? If not we need to create a dummy object per instance to set the status of the inspector service and then check it. What do you think?

2023-04-24 06:46 UTC, jfagoagas commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +class Inspector(BaseModel):
Can we include the status here to set if the service is enabled or not?

2023-04-24 07:53 UTC, sergargar commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +                    regional_client.get_configuration()
Please, parallelize this function by region using __threading_call__

2023-04-24 08:32 UTC, gabrielsoltz commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +                    regional_client.get_configuration()
No, nothing useful for the context; I'm only using it to check if inspector is enabled.

2023-04-24 08:40 UTC, gabrielsoltz commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +                    regional_client.get_configuration()
✅

2023-04-24 08:41 UTC, gabrielsoltz commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +                    if error.response["Error"]["Code"] == "ResourceNotFoundException":
is not a global service, we are already doing that with the object `Inspector`

2023-04-24 08:51 UTC, MrCloudSec commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +                        f"{self.region} -- {error.__class__.__name__}[{error.__traceback__.tb_lineno}]: {error}"
```suggestion
                        f"{regional_client.region} -- {error.__class__.__name__}[{error.__traceback__.tb_lineno}]: {error}"
```

2023-04-24 09:09 UTC, gabrielsoltz commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +class Inspector(BaseModel):
I added the status, it makes sense to understand where inspector is enabled/disabled, thanks!

2023-04-24 09:36 UTC, gabrielsoltz commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +class Inspector(BaseModel):
i changed this function to use https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/inspector2/client/batch_get_account_status.html

2023-04-24 09:36 UTC, gabrielsoltz commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +                    regional_client.get_configuration()
i changed this function to use https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/inspector2/client/batch_get_account_status.html

2023-04-24 09:36 UTC, gabrielsoltz commented on prowler/providers/aws/services/inspector2/inspector2_service.py
> +                    if error.response["Error"]["Code"] == "ResourceNotFoundException":
i changed this function to use https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/inspector2/client/batch_get_account_status.html

2023-04-24 10:06 UTC, sergargar approved these changes
Great job!!

2023-04-24 10:15 UTC, jfagoagas approved these changes

2023-04-24 10:15 UTC, merged