feat(NetworkFirewall): New Service and Check
toniblyx/prowler pull request #2261
Opened 2023-04-23 21:31 UTC by gabrielsoltz

### Context

Ahora si, one more! New `networkfirewall` service!
Check: networkfirewall_in_all_vpc (medium): Ensure all VPCs have Network Firewall enabled

Without a network firewall, it can be difficult to monitor and control traffic within the VPC. This can make it harder to detect and prevent attacks or unauthorized access to resources.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-24 10:59 UTC, sergargar commented on prowler/providers/aws/services/networkfirewall/networkfirewall_service.py
> +                f"{error.__class__.__name__}:{error.__traceback__.tb_lineno} -- {error}"
Can you add the region of the regional_client in the error?

2023-04-24 12:04 UTC, sergargar commented on prowler/providers/aws/services/networkfirewall/networkfirewall_in_all_vpc/networkfirewall_in_all_vpc.metadata.json
> +      "Other": "",
```suggestion
      "Other": "https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/NetworkFirewall/network-firewall-in-use.html",
```

2023-04-24 15:49 UTC, gabrielsoltz commented on prowler/providers/aws/services/networkfirewall/networkfirewall_service.py
> +                f"{error.__class__.__name__}:{error.__traceback__.tb_lineno} -- {error}"
changed ✅

2023-04-25 06:08 UTC, jfagoagas requested changes

2023-04-25 06:08 UTC, jfagoagas commented on prowler/providers/aws/services/networkfirewall/networkfirewall_in_all_vpc/networkfirewall_in_all_vpc.metadata.json
> +  "ResourceIdTemplate": "arn:partition:service::account-id:organization/organization-id",
Change this please!

2023-04-25 06:08 UTC, jfagoagas commented on prowler/providers/aws/services/networkfirewall/networkfirewall_in_all_vpc/networkfirewall_in_all_vpc.metadata.json
> +      "CLI": "aws network-firewall list-firewalls",
Do you have the command to enable it?

2023-04-25 06:08 UTC, jfagoagas commented on prowler/providers/aws/services/networkfirewall/networkfirewall_in_all_vpc/networkfirewall_in_all_vpc.py
> +            report.resource_arn = ""
Could you please fill this ARN?

2023-04-25 06:08 UTC, jfagoagas commented on prowler/providers/aws/services/networkfirewall/networkfirewall_service.py
> +                                name=network_firewall["FirewallName"],
Please use the `dict.get()` syntax here.

2023-04-25 06:08 UTC, jfagoagas commented on prowler/providers/aws/services/networkfirewall/networkfirewall_service.py
> +                ]["Type"]
Please use the `dict.get()` syntax here.

2023-04-25 08:04 UTC, gabrielsoltz commented on prowler/providers/aws/services/networkfirewall/networkfirewall_in_all_vpc/networkfirewall_in_all_vpc.py
> +            report.resource_arn = ""
with what? VPC object doesn't provide arn.

2023-04-25 08:06 UTC, gabrielsoltz commented on prowler/providers/aws/services/networkfirewall/networkfirewall_in_all_vpc/networkfirewall_in_all_vpc.metadata.json
> +      "CLI": "aws network-firewall list-firewalls",
added it ✅

2023-04-25 08:06 UTC, gabrielsoltz commented on prowler/providers/aws/services/networkfirewall/networkfirewall_service.py
> +                                name=network_firewall["FirewallName"],
changed ✅

2023-04-25 08:06 UTC, gabrielsoltz commented on prowler/providers/aws/services/networkfirewall/networkfirewall_service.py
> +                ]["Type"]
changed ✅

2023-04-26 09:38 UTC, jfagoagas approved these changes
Good to go! 🚀

2023-04-26 09:38 UTC, jfagoagas commented on prowler/providers/aws/services/networkfirewall/networkfirewall_in_all_vpc/networkfirewall_in_all_vpc.py
> +            report.resource_arn = ""
Good point!

2023-04-26 09:58 UTC, merged