feat(Organizations): New check organizations_tags_policies_enabled_and_attached
toniblyx/prowler pull request #2287
Opened 2023-04-26 22:44 UTC by gabrielsoltz

### Context

New `organizations` check: `organizations_tags_policies_enabled_and_attached`

Check if AWS Organizations tags policies are enabled and attached.

I found that the organizations' service was only listing SCP policies, i improved the service so we list any type of available policies (`available_policies = ["SERVICE_CONTROL_POLICY","TAG_POLICY","BACKUP_POLICY","AISERVICES_OPT_OUT_POLICY",]`), after the doing this, i noticed the check `organizations_scp_check_deny_regions` was not validating if the policy being checked was SCP, so i added that "fix" on that check as well. 

I tried using Moto for the tests, but sadly, TAG_POLICIES are not implemented so I ended up mocking it.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-27 07:02 UTC, jfagoagas requested changes

2023-04-27 07:02 UTC, jfagoagas commented on prowler/providers/aws/services/organizations/organizations_service.py
> +        ]
Could you move this to the top of the service to set it like a constant?

2023-04-27 07:02 UTC, jfagoagas commented on prowler/providers/aws/services/organizations/organizations_tags_policies_enabled_and_attached/organizations_tags_policies_enabled_and_attached.metadata.json
> +  "CheckTitle": "Check if AWS Organizations tags policies are enabled and attached.",
```suggestion
  "CheckTitle": "Check if an AWS Organization has tags policies enabled and attached.",
```

2023-04-27 07:02 UTC, jfagoagas commented on prowler/providers/aws/services/organizations/organizations_tags_policies_enabled_and_attached/organizations_tags_policies_enabled_and_attached.metadata.json
> +  "Description": "Check if AWS Organizations tags policies are enabled and attached.",
```suggestion
  "Description": "Check if an AWS Organization has tags policies enabled and attached.",
```

2023-04-27 07:02 UTC, jfagoagas commented on prowler/providers/aws/services/organizations/organizations_tags_policies_enabled_and_attached/organizations_tags_policies_enabled_and_attached.py
> +                    report.status_extended = f"TAG Policies exist at the organization {org.id} level but not attached"
```suggestion
                    report.status_extended = f"AWS Organization {org.id} has tag policies enabled but not attached"
```

2023-04-27 07:02 UTC, jfagoagas commented on prowler/providers/aws/services/organizations/organizations_tags_policies_enabled_and_attached/organizations_tags_policies_enabled_and_attached.py
> +                        report.status_extended = f"TAG Policies exist at the organization {org.id} level and are attached"
```suggestion
                        report.status_extended = f"AWS Organization {org.id} has tag policies enabled and attached to an AWS account"
```

2023-04-27 11:42 UTC, jfagoagas commented on tests/providers/aws/services/organizations/organizations_tags_policies_enabled_and_attached/organizations_tags_policies_enabled_and_attached_test.py
> +    Organizations,
```suggestion
```

2023-04-27 12:10 UTC, gabrielsoltz commented on prowler/providers/aws/services/organizations/organizations_service.py
> +        ]
🔝

2023-04-28 05:34 UTC, jfagoagas requested changes

2023-04-28 05:34 UTC, jfagoagas commented on prowler/providers/aws/services/organizations/organizations_tags_policies_enabled_and_attached/organizations_tags_policies_enabled_and_attached.metadata.json
> +  "Risk": "If AWS Organizations tags policies are not enabled and attached, it is not possible to enforce tags on AWS resources.",
```suggestion
  "Risk": "If an AWS Organization tags policies are not enabled and attached, it is not possible to enforce tags on AWS resources.",
```

2023-04-28 05:34 UTC, jfagoagas commented on tests/providers/aws/services/organizations/organizations_service_test.py
> -        assert len(organizations.policies) == 2
Why are you removing this assertion?

2023-04-28 05:34 UTC, jfagoagas commented on tests/providers/aws/services/organizations/organizations_tags_policies_enabled_and_attached/organizations_tags_policies_enabled_and_attached_test.py
> +                master_id="",
What happens if you run this check outside the management account?

2023-04-28 05:34 UTC, jfagoagas commented on tests/providers/aws/services/organizations/organizations_tags_policies_enabled_and_attached/organizations_tags_policies_enabled_and_attached_test.py
> +                master_id="",
Do we have a test for that?

2023-04-28 09:30 UTC, gabrielsoltz commented on tests/providers/aws/services/organizations/organizations_service_test.py
> -        assert len(organizations.policies) == 2
Because now we get all policies, and I think the amount we found makes no more sense (it's like 8 by default, as far as I understood, all of them are "awsmanaged"). The only one we care about here is the one I'm creating using create_policy, and that's the only one I want to assert.

2023-04-28 09:39 UTC, gabrielsoltz commented on tests/providers/aws/services/organizations/organizations_tags_policies_enabled_and_attached/organizations_tags_policies_enabled_and_attached_test.py
> +                master_id="",
This is what we are testing here.
We create a NOT_AVAILABLE status when we get a ClientError: https://github.com/prowler-cloud/prowler/blob/3a59b0d7f593d20b33ee40cafb5722ace87fe37a/prowler/providers/aws/services/organizations/organizations_service.py#LL52C1-L52C1

2023-04-28 14:07 UTC, jfagoagas commented on tests/providers/aws/services/organizations/organizations_service_test.py
> -        assert len(organizations.policies) == 2
Awesome, thanks for the explanation!

2023-04-28 14:13 UTC, jfagoagas approved these changes
Let's go 🚀

2023-04-28 14:14 UTC, merged