fix(sts): Use the right region to validate credentials
toniblyx/prowler pull request #2349
Opened 2023-05-12 08:27 UTC by jfagoagas

### Context

Please include relevant motivation and context for this PR.

### Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-12 13:33 UTC, jfagoagas commented on docs/tutorials/aws/regions-and-partitions.md
> +For the AWS ISO partitions, which are known as "secret partitions" and are air-gapped from the internet there is no builtin way to scanned it. In this scenario if you want to audit an AWS Account in
```suggestion
For the AWS ISO partitions, which are known as "secret partitions" and are air-gapped from the internet there is no builtin way to scan it. In this scenario if you want to audit an AWS Account in one of the AWS ISO partitions you should manually update the [aws_regions_by_service.json](https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/aws_regions_by_service.json) and include the partition, region and services, e.g.:
```

2023-05-12 14:41 UTC, jfagoagas commented on docs/tutorials/aws/regions-and-partitions.md
> +>> With this option all the partition regions will be scanned without the need of use the `-f/--region` flag
```suggestion
> With this option all the partition regions will be scanned without the need of use the `-f/--region` flag
```

2023-05-16 13:13 UTC, sergargar requested changes
Please, review my comments.

2023-05-16 13:13 UTC, sergargar commented on mkdocs.yml
> +          - Regions and Partition: tutorials/aws/regions-and-partitions.md
```suggestion
          - AWS Regions and Partitions: tutorials/aws/regions-and-partitions.md
```

2023-05-16 13:13 UTC, sergargar commented on prowler/providers/aws/lib/arn/arn.py
>          arn_parsed = arnparse(arn)
can you remove `arnparse` library?

2023-05-16 13:42 UTC, MrCloudSec commented on prowler/providers/aws/lib/arn/arn.py
>          arn_parsed = arnparse(arn)
Done

2023-05-16 13:51 UTC, sergargar approved these changes, later dismissed

2023-05-18 13:51 UTC, sergargar approved these changes
amazing 🤯

2023-05-18 13:51 UTC, merged