chore(docs): add summary table to README.md
toniblyx/prowler pull request #2402
Opened 2023-05-23 15:55 UTC by toniblyx

### Context

To help users understand what they will be able to do with Prowler, we have added a table with details of what it is covered so far and what is coming soon.
![Screenshot 2023-05-23 at 17 54 48](https://github.com/prowler-cloud/prowler/assets/3985464/89c4776c-e594-467a-9110-89c7a990faf8)

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-05-23 20:18 UTC, sergargar requested changes
I love it! Please check my comments.

2023-05-23 20:18 UTC, sergargar commented on README.md
> +|
```suggestion
| Provider | Checks | Services | [Compliance Frameworks](https://docs.prowler.cloud/en/latest/tutorials/compliance/) | [Categories](https://docs.prowler.cloud/en/latest/tutorials/misc/#categories) |
|---|---|---|---|---|
| AWS | 281 | 54 -> `prowler aws --list-services` | 21 -> `prowler aws --list-compliance` | 6 -> `prowler aws --list-categories` |
| GCP | 43 | 7 -> `prowler gcp --list-services` | CIS soon | 0 -> `prowler gcp --list-categories`|
| Azure | 20 | 3 -> `prowler gcp --list-services` | CIS soon | 1 -> `prowler azure --list-categories` |
| Kubernetes | Planned | - | - | - |
|
```

2023-05-23 20:18 UTC, sergargar commented on README.md
> +|
How about putting arrows?

2023-05-23 20:18 UTC, sergargar commented on README.md
> +|
There is an extra pipe | at the end

2023-05-23 20:18 UTC, sergargar commented on README.md
> +|
```suggestion
| Provider | Checks | Services | [Compliance Frameworks](https://docs.prowler.cloud/en/latest/tutorials/compliance/) | [Categories](https://docs.prowler.cloud/en/latest/tutorials/misc/#categories) |
|---|---|---|---|---|
| AWS | 281 | 54: `prowler aws --list-services` | 21: `prowler aws --list-compliance` | 6: `prowler aws --list-categories` |
| GCP | 43 | 7: `prowler gcp --list-services` | CIS soon | - `prowler gcp --list-categories`|
| Azure | 20 | 3: `prowler gcp --list-services` | CIS soon | 1: `prowler azure --list-categories` |
| Kubernetes | Planned | - | - | - |
```

2023-05-23 20:19 UTC, sergargar commented on README.md
> +|
There is an extra pipe | at the end.

2023-05-24 10:15 UTC, toniblyx commented on README.md
> +|
No hahaha

2023-05-24 10:18 UTC, toniblyx commented on README.md
> +|
needed for the last line of the table

2023-05-24 10:34 UTC, sergargar commented on README.md
> +|
It is not needed

2023-05-24 11:29 UTC, sergargar approved these changes, later dismissed
good job!

2023-05-24 11:37 UTC, sergargar commented on README.md
> +| GCP | 43 | 7 -> `prowler gcp --list-services` | CIS soon | 0 -> `prowler gcp --list-categories`|
```suggestion
| GCP | 47 | 7 -> `prowler gcp --list-services` | CIS soon | 0 -> `prowler gcp --list-categories`|
```

2023-05-24 11:40 UTC, sergargar approved these changes

2023-05-24 11:56 UTC, merged