Add 6 new AWS rules
toniblyx/prowler pull request #2645
Opened 2023-07-31 17:45 UTC by jit-contrib

### Context
Adding 6 new AWS rules

### Description
This PR adds 6 new GCP rules alongside with respective unit tests.

List of new added rules:

* cloudtrail_management_exist_with_multi_region_enabled
* dlm_ebs_snapshot_policy_exists
* documentdb_instance_storage_encrypted
* ec2_ebs_snapshots_exists
* secretsmanager_check_if_service_is_in_use
* ssm_check_if_secure_strings_is_in_use

### License
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-01 07:53 UTC, jfagoagas requested changes
Thanks for all these new checks @jit-contrib !!

I left some comments but as a general recommendation:
- Do not forget to fill all the `report` fields like `region`, `arn` or `id`. We cannot leave these fields empty.
- It is important to fill the `Risk`, `RelatedUrl`, `Recommendation` and `Remediation` in the metadata.

I'll review the tests once all the comments are addressed.

Thanks!

2023-08-01 07:53 UTC, jfagoagas commented on poetry.lock
Please, make sure that you don't push changes for the `poetry.lock` since it's managed automatically by our Github Actions.

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/cloudtrail/cloudtrail_management_exist_with_multi_region_enabled/cloudtrail_management_exist_with_multi_region_enabled.metadata.json
> +  "Risk": "",
Please, fill the `Risk` here.

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/cloudtrail/cloudtrail_management_exist_with_multi_region_enabled/cloudtrail_management_exist_with_multi_region_enabled.py
> +                            report.status_extended = f"Trail {trail.name} has multi-region and management events logs enabled"
```suggestion
                            report.status_extended = f"Trail {trail.name} is multi-region, is logging and have management events logs enabled"
```

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/cloudtrail/cloudtrail_management_exist_with_multi_region_enabled/cloudtrail_management_exist_with_multi_region_enabled.py
> +        )
I this report block the following fields are missing:
```
report.region = trail.region
report.resource_id = trail.name
report.resource_arn = trail.arn
report.resource_tags = trail.tags
```

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/cloudtrail/cloudtrail_management_exist_with_multi_region_enabled/cloudtrail_management_exist_with_multi_region_enabled.py
> +            findings.append(report)
I think this block can be simplified with a boolean variable to break the loop.

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/dlm/dlm_ebs_snapshot_policy_exists/dlm_ebs_snapshot_policy_exists.metadata.json
I'd change policies here to `lifecycle policies`, WDYT?

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/dlm/dlm_ebs_snapshot_policy_exists/dlm_ebs_snapshot_policy_exists.metadata.json
> +  },
Did you check these fields?

https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/DLM/ebs-snapshot-automation.html

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/dlm/dlm_service.py
> +        self.__threading_call__(self.__get_lifecycle_policies__)
All this fields have been moved to a new `AWSService` class here https://github.com/prowler-cloud/prowler/pull/2638

```suggestion
class DLM(AWSService):
    def __init__(self, audit_info):
        # Call AWSService's __init__
        super().__init__(__class__.__name__, audit_info)
        self.lifecycle_policies = []
        self.__threading_call__(self.__get_lifecycle_policies__)
```

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/dlm/dlm_service.py
> +            t.join()
Moved to the `AWSService` class too.

```suggestion
```

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/documentdb/documentdb_service.py
> +            t.join()
All this fields have been moved to a new `AWSService` class here https://github.com/prowler-cloud/prowler/pull/2638

```suggestion
class DocumentDB(AWSService):
    def __init__(self, audit_info):
        # Call AWSService's __init__
        super().__init__("docdb", audit_info)
        self.db_instances = []
        self.__threading_call__(self.__describe_db_instances__)
```

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/documentdb/documentdb_instance_storage_encrypted/documentdb_instance_storage_encrypted.metadata.json
> +  "ResourceIdTemplate": "",
Please fill the ARN model for this resource.

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/documentdb/documentdb_instance_storage_encrypted/documentdb_instance_storage_encrypted.metadata.json
> +      "Other": "",
```suggestion
      "Other": "https://www.trendmicro.com/cloudoneconformity-staging/knowledge-base/aws/DocumentDB/encryption-enabled.html",
```

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/documentdb/documentdb_instance_storage_encrypted/documentdb_instance_storage_encrypted.metadata.json
> +      "Url": ""
Include an URI from the AWS documentation here if possible.

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/documentdb/documentdb_instance_storage_encrypted/documentdb_instance_storage_encrypted.metadata.json
> +  "RelatedUrl": "",
Include an URI from the AWS documentation here if possible.

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/documentdb/documentdb_instance_storage_encrypted/documentdb_instance_storage_encrypted.py
> +            report.resource_id = db_instance.id
`report.resource_arn` is missing here.

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/documentdb/documentdb_service.py
> +    id: str
Please include the ARN here using https://docs.aws.amazon.com/documentdb/latest/developerguide/documentdb-arns.html

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/ec2/ec2_ebs_snapshots_exists/ec2_ebs_snapshots_exists.metadata.json
> +  },
Please fill all these fields if possible.

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/ec2/ec2_ebs_snapshots_exists/ec2_ebs_snapshots_exists.py
> +        report.status_extended = "EBS Snapshots don't exist."
In this report block the following fields are missing:
```
report.region = trail.region
report.resource_id = trail.name
report.resource_arn = trail.arn
report.resource_tags = trail.tags
```

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/secretsmanager/secretsmanager_check_if_service_is_in_use/secretsmanager_check_if_service_is_in_use.py
> +        report = Check_Report_AWS(self.metadata())
```
report.region = trail.region
report.resource_id = trail.name
report.resource_arn = trail.arn
report.resource_tags = trail.tags
```

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/ssm/ssm_check_if_secure_strings_is_in_use/ssm_check_if_secure_strings_is_in_use.py
> +        report = Check_Report_AWS(self.metadata())
```
report.region = trail.region
report.resource_id = trail.name
report.resource_arn = trail.arn
report.resource_tags = trail.tags
```

2023-08-01 07:53 UTC, jfagoagas commented on prowler/providers/aws/services/ssm/ssm_check_if_secure_strings_is_in_use/ssm_check_if_secure_strings_is_in_use.py
> +            report.status_extended = "SSm secure strings is not in use."
```suggestion
            report.status_extended = "SSM secure strings is not in use."
```

2023-08-01 08:02 UTC, jfagoagas commented
I have a question because I don’t see the point of checking the usage of SecretsManager, SSM or EBS because these new checks are validating if you are using it but not if you are using it securely and also there are some other checks that can be used to get the same result, e.g. if the check `secretsmanager_automatic_rotation_enabled` generates findings means that you are using SecretsManager.

2023-08-03 16:23 UTC, jit-contrib commented
This PR can be closed, since the changes suggested in your comments were replicated in the following PR https://github.com/prowler-cloud/prowler/pull/2675

2023-09-25 07:27 UTC, closed without merging