Dump all checks as a json file.
toniblyx/prowler pull request #2683
Opened 2023-08-07 12:43 UTC by jchrisfarris

### Context

This PR adds a CLI option to dump all the available checks into a json file that can be consumed by the `--checks-file` flag. 

### Description

```bash
prowler aws -jb > my_checks.json
# user edits my_checks.json to remove the ones they don't want
prowler aws --checks-file my_checks.json
```

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-07 12:53 UTC, jfagoagas requested changes
Thanks @jchrisfarris, this is great but please check the comments.

2023-08-07 12:53 UTC, jfagoagas commented on prowler/__main__.py
> +    if args.list_checks_json:
Could you include this within a function in the `check` lib?

I think you can reutilize the code there.

2023-08-07 12:53 UTC, jfagoagas commented on prowler/lib/cli/parser.py
> +        list_group.add_argument(
For new flags and arguments we are not including short options for the flags, but we can leave it if you find it useful.

We have to include a test for this new option.

2023-08-07 12:56 UTC, jchrisfarris commented on prowler/lib/cli/parser.py
> +        list_group.add_argument(
Short code isn't needed. We can remove. I'll look at the other request when I circle back to this.

2023-08-21 15:14 UTC, jfagoagas approved these changes
Awesome, thanks @jchrisfarris !

2023-08-21 15:35 UTC, merged