chore(iam_role_cross_service_confused_deputy_prevention): add ResourceAccount and PrincipalAccount conditions
toniblyx/prowler pull request #2689
Opened 2023-08-08 09:40 UTC by sergargar

### Description

add ResourceAccount and PrincipalAccount conditions in `iam_role_cross_service_confused_deputy_prevention` check

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-08 12:24 UTC, jfagoagas requested changes

2023-08-08 12:24 UTC, jfagoagas commented on prowler/providers/aws/services/iam/iam_role_cross_service_confused_deputy_prevention/iam_role_cross_service_confused_deputy_prevention.py
> +                                )
Please, try to use the `condition_parser` in this check and include these condition keys in the library if not present.

Also update the tests for both the library and the check to cover these new cases.

2023-08-09 08:00 UTC, MrCloudSec commented on prowler/providers/aws/services/iam/iam_role_cross_service_confused_deputy_prevention/iam_role_cross_service_confused_deputy_prevention.py
> +                                )
Done

2023-08-09 08:28 UTC, jfagoagas approved these changes
<img src="https://media2.giphy.com/media/KEYbcgR8oKQzwpwvLU/giphy-downsized-medium.gif"/>

2023-08-09 08:41 UTC, merged