feat(controltower): add allowlist for controltower resources
toniblyx/prowler pull request #2953
Opened 2023-10-20 09:02 UTC by sergargar

### Description

Add Allowlist for AWS ControlTower resources that are created by default when setting up a landing zone.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-10-20 09:29 UTC, toniblyx requested changes

2023-10-20 09:29 UTC, toniblyx commented on prowler/config/aws_controltower_allowlist.yaml
> +Allowlist:
```suggestion
### The following file includes all resources created by AWS Control Tower ###
Allowlist:
```

2023-10-20 10:40 UTC, toniblyx submitted a review, later dismissed

2023-10-20 10:40 UTC, toniblyx commented on docs/tutorials/allowlist.md
> +prowler aws --allowlist prowler/config/aws_controltower_allowlist.yaml
do we support multiple files here? I don´t think so.

2023-10-24 14:45 UTC, n4ch04 approved these changes

2023-10-24 14:45 UTC, merged