Added AWS role session name parameter
toniblyx/prowler pull request #3234
Opened 2024-01-02 07:55 UTC by Fennerr

### Context

Added as per this request in the prowler slack: https://prowler-workspace.slack.com/archives/C0451NDLC4X/p1704113278185009

### Description

Added a parameter to specify the RoleSessionName value passed to AWS api when performing assume-role calls.

I have not tested this myself. I have requested that the requestee tests it out.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-01-05 07:57 UTC, jfagoagas requested changes
Thanks for this new flag @Fennerr ! I left some comments to include tests for the new argument and function to validate it. We'll do that as soon as we can.

2024-01-05 07:57 UTC, jfagoagas commented on prowler/providers/aws/lib/arguments/arguments.py
> +    aws_auth_subparser.add_argument(
We have to include tests for this new argument.

2024-01-05 07:57 UTC, jfagoagas commented on prowler/providers/aws/lib/arguments/arguments.py
> +def validate_role_session_name(session_name):
We have to include tests for this new function.

2024-01-05 16:58 UTC, Fennerr commented
Okay awesome. Something I just realised is that I didnt cover setting a role name for the call to assume role when using an Organizations Role.

For now I commited a change to assume_role:
```python
role_session_name = (
    assumed_role_info.role_session_name
    if assumed_role_info.role_session_name
    else "ProwlerAsessmentSession"
)
``` 

Just to ensure that any calls to assume_role will be guaranteed to have a role session name

This is why tests are important!

2024-01-08 11:39 UTC, jfagoagas approved these changes
Awesome!! 

Thanks @Fennerr and @sergargar !! 🚀

2024-01-08 11:40 UTC, sergargar commented
Testing and docs were added!

2024-01-08 11:49 UTC, merged