chore(arn): improve resource ARNs in checks
toniblyx/prowler pull request #3388
Opened 2024-02-12 15:07 UTC by sergargar

### Description

Improve resource ARNs in checks where we had the Account ARN, now Prowler will have the correct ARN for each resource.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-16 10:58 UTC, jfagoagas requested changes
As a general recommendation, save that generic ARNs in the services and then get that in the checks, we should define that in just one place. Check that please.

2024-02-16 10:58 UTC, jfagoagas commented on prowler/providers/aws/services/backup/backup_plans_exist/backup_plans_exist.py
> +            report.resource_arn = f"arn:{backup_client.audited_partition}:backup:{backup_client.region}:{backup_client.audited_account}:backup-plan"
Please add this to the Backup service.

2024-02-16 10:58 UTC, jfagoagas commented on prowler/providers/aws/services/backup/backup_plans_exist/backup_plans_exist.py
> +            report.resource_arn = f"arn:{backup_client.audited_partition}:backup:{backup_client.region}:{backup_client.audited_account}:backup-plan"
This applies to all the backup checks.

2024-02-16 11:00 UTC, jfagoagas commented on prowler/providers/aws/services/backup/backup_plans_exist/backup_plans_exist.py
> +            report.resource_arn = f"arn:{backup_client.audited_partition}:backup:{backup_client.region}:{backup_client.audited_account}:backup-plan"
Maybe you can define those ARNs in a single place to use that also for the tests. Maybe it's better to have something in the `lib/arn` with the service generic ARNs.

2024-02-19 09:19 UTC, jfagoagas requested changes
Please, modify Prowler Developer Guide to reflect this change here https://docs.prowler.com/projects/prowler-open-source/en/latest/developer-guide/checks/#resource-id-name-and-arn

2024-02-28 16:08 UTC, MrCloudSec commented on prowler/providers/aws/services/backup/backup_plans_exist/backup_plans_exist.py
> +            report.resource_arn = f"arn:{backup_client.audited_partition}:backup:{backup_client.region}:{backup_client.audited_account}:backup-plan"
Good point, it would be a nice-to-have. But I see it complicated, since each check can have a different resource type and we need to use the information of each service.

2024-02-28 17:08 UTC, jfagoagas commented on docs/developer-guide/checks.md
> +        - Root resource --> Root ARN `f"arn:{service_client.audited_partition}:<service_name>:{service_client.region}:{service_client.audited_account}:<resource_type>"`
Name the result differently than `root`, maybe Service ARN or Resource Type ARN

2024-02-28 17:30 UTC, sergargar commented on prowler/providers/aws/services/backup/backup_plans_exist/backup_plans_exist.py
> +            report.resource_arn = f"arn:{backup_client.audited_partition}:backup:{backup_client.region}:{backup_client.audited_account}:backup-plan"
Done! I have added them in each service class.

2024-03-05 10:14 UTC, jfagoagas requested changes

2024-03-05 10:14 UTC, jfagoagas commented on prowler/providers/aws/services/backup/backup_service.py
> +        self.backup_plan_arn_template = f"arn:{self.audited_partition}:backup:{self.region}:{self.audited_account}:backup-plan"
`self.region` or `client.region` since we want to include the resource region here.

2024-03-05 10:15 UTC, jfagoagas commented on prowler/providers/aws/services/backup/backup_service.py
> +        self.backup_plan_arn_template = f"arn:{self.audited_partition}:backup:{self.region}:{self.audited_account}:backup-plan"
This applies to all the services that has an ARN template.

2024-03-05 10:37 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_changes_to_network_acls_alarm_configured/cloudwatch_changes_to_network_acls_alarm_configured.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas requested changes

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_changes_to_network_gateways_alarm_configured/cloudwatch_changes_to_network_gateways_alarm_configured.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_changes_to_network_route_tables_alarm_configured/cloudwatch_changes_to_network_route_tables_alarm_configured.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_changes_to_vpcs_alarm_configured/cloudwatch_changes_to_vpcs_alarm_configured.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_and_alarm_for_aws_config_configuration_changes_enabled/cloudwatch_log_metric_filter_and_alarm_for_aws_config_configuration_changes_enabled.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_and_alarm_for_cloudtrail_configuration_changes_enabled/cloudwatch_log_metric_filter_and_alarm_for_cloudtrail_configuration_changes_enabled.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_authentication_failures/cloudwatch_log_metric_filter_authentication_failures.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_aws_organizations_changes/cloudwatch_log_metric_filter_aws_organizations_changes.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_disable_or_scheduled_deletion_of_kms_cmk/cloudwatch_log_metric_filter_disable_or_scheduled_deletion_of_kms_cmk.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_for_s3_bucket_policy_changes/cloudwatch_log_metric_filter_for_s3_bucket_policy_changes.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_policy_changes/cloudwatch_log_metric_filter_policy_changes.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_root_usage/cloudwatch_log_metric_filter_root_usage.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_security_group_changes/cloudwatch_log_metric_filter_security_group_changes.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_sign_in_without_mfa/cloudwatch_log_metric_filter_sign_in_without_mfa.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_unauthorized_api_calls/cloudwatch_log_metric_filter_unauthorized_api_calls.py
>          report.region = cloudwatch_client.region
```suggestion
        report.region = logs_client.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/config/config_recorder_all_regions_enabled/config_recorder_all_regions_enabled.py
>              report.region = recorder.region
```suggestion
            report.region = config.region
```

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/dlm/dlm_ebs_snapshot_lifecycle_policy_exists/dlm_ebs_snapshot_lifecycle_policy_exists.py
>                  report.region = region
Check this region please.

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/drs/drs_job_exist/drs_job_exist.py
>              report.region = drs.region
Check this region please.

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/ec2/ec2_ebs_default_encryption/ec2_ebs_default_encryption.py
>              report.region = ebs_encryption.region
Check this region please.

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/emr/emr_cluster_account_public_block_enabled/emr_cluster_account_public_block_enabled.py
>              report.region = region
Check this region please.

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/glue/glue_data_catalogs_connection_passwords_encryption_enabled/glue_data_catalogs_connection_passwords_encryption_enabled.py
>                  report.region = encryption.region
Check this region please.

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/glue/glue_data_catalogs_metadata_encryption_enabled/glue_data_catalogs_metadata_encryption_enabled.py
>                  report.region = encryption.region
Check this region please.

2024-03-05 10:48 UTC, jfagoagas commented on prowler/providers/aws/services/macie/macie_is_enabled/macie_is_enabled.py
>              report.region = session.region
Check this region please.

2024-03-05 13:10 UTC, jfagoagas submitted a review, later dismissed
Great improvement @sergargar 🚀

2024-03-05 14:53 UTC, jfagoagas submitted a review, later dismissed

2024-03-05 17:10 UTC, jfagoagas approved these changes
👍

2024-03-05 17:10 UTC, merged