New Azure checks related to PostgreSQL service
toniblyx/prowler pull request #3396
Opened 2024-02-13 11:59 UTC by pedrooot

### Context
This pr add 7 new checks related to PostgreSQL service

### Description

The new checks are:

- [ ] postgresql_flexible_server_enforce_ssl_enabled
- [ ] postgresql_flexible_server_log_checkpoints_on
- [ ] postgresql_flexible_server_log_connections_on
- [ ] postgresql_flexible_server_log_disconnections_on
- [ ] postgresql_flexible_server_connection_throttling_on
- [ ] postgresql_flexible_server_log_retention_days_greater_3
- [ ] postgresql_flexible_server_allow_access_services_disabled

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-16 10:02 UTC, sergargar requested changes
Please, check my comments.

2024-02-16 10:02 UTC, MrCloudSec commented on package-lock.json
> +}
Please, remove this file.

2024-02-16 10:02 UTC, MrCloudSec commented on prowler/providers/azure/services/postgresql/postgresql_flexible_server_enforce_ssl_enabled/postgresql_flexible_server_enforce_ssl_enabled.metadata.json
> +      "Terraform": ""
```suggestion
      "Terraform": "https://docs.bridgecrew.io/docs/bc_azr_networking_10#terraform"
```

2024-02-16 10:02 UTC, MrCloudSec commented on prowler/providers/azure/services/postgresql/postgresql_flexible_server_enforce_ssl_enabled/postgresql_flexible_server_enforce_ssl_enabled.metadata.json
> +      "Other": "https://docs.bridgecrew.io/docs/bc_azr_networking_10",
Is there a TrendMicro link for this?

2024-02-16 10:02 UTC, MrCloudSec commented on prowler/providers/azure/services/postgresql/postgresql_service.py
> +                            ),
Can you set it up like the other ones, please?

2024-02-16 10:02 UTC, MrCloudSec commented on pyproject.toml
> +azure-mgmt-rdbms = "^10.1.0"
```suggestion
azure-mgmt-rdbms = "10.1.0"
```

2024-02-16 10:54 UTC, pedrooot commented on package-lock.json
> +}
Done!

2024-02-16 10:54 UTC, pedrooot commented on prowler/providers/azure/services/postgresql/postgresql_flexible_server_enforce_ssl_enabled/postgresql_flexible_server_enforce_ssl_enabled.metadata.json
> +      "Terraform": ""
Done!

2024-02-16 10:55 UTC, pedrooot commented on prowler/providers/azure/services/postgresql/postgresql_flexible_server_enforce_ssl_enabled/postgresql_flexible_server_enforce_ssl_enabled.metadata.json
> +      "Other": "https://docs.bridgecrew.io/docs/bc_azr_networking_10",
No, TrendMicro is not available for this one

2024-02-16 10:55 UTC, pedrooot commented on prowler/providers/azure/services/postgresql/postgresql_service.py
> +                            ),
Done!

2024-02-16 10:56 UTC, pedrooot commented on pyproject.toml
> +azure-mgmt-rdbms = "^10.1.0"
Done!

2024-02-19 10:38 UTC, pedrooot commented
Updated to: https://github.com/prowler-cloud/prowler/pull/3409

2024-02-19 10:39 UTC, closed without merging