feat(azure): add new check related with Public IPs in Shodan.io
toniblyx/prowler pull request #3433
Opened 2024-02-26 09:18 UTC by pedrooot

### Context

This pr adds a new check:

* network_public_ip_shodan

and fixes typo in all tests that don´t include azure_fixtures

### Description

This check ensures that no public ip addresses are shown in shodan

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-02-26 11:15 UTC, sergargar commented on prowler/providers/azure/services/network/network_service.py
> +        self.audit_info = audit_info
```suggestion
```

2024-02-26 11:15 UTC, sergargar commented on prowler/providers/azure/services/network/network_public_ip_shodan/network_public_ip_shodan.py
> +        shodan_api_key = network_client.audit_info.audit_config.get("shodan_api_key")
```suggestion
        shodan_api_key = network_client.audit_config.get("shodan_api_key")
```

2024-02-26 11:16 UTC, sergargar commented on prowler/providers/azure/services/network/network_public_ip_shodan/network_public_ip_shodan.py
> +                                f"Elastic IP {ip.ip_address} is not listed in Shodan."
```suggestion
                                f"Public IP {ip.ip_address} is not listed in Shodan."
```

2024-02-26 11:18 UTC, sergargar requested changes
Please, review my comments.

2024-02-26 11:19 UTC, pedrooot commented on prowler/providers/azure/services/network/network_service.py
> +        self.audit_info = audit_info
Done

2024-02-26 11:20 UTC, pedrooot commented on prowler/providers/azure/services/network/network_public_ip_shodan/network_public_ip_shodan.py
> +        shodan_api_key = network_client.audit_info.audit_config.get("shodan_api_key")
Done

2024-02-26 11:20 UTC, pedrooot commented on prowler/providers/azure/services/network/network_public_ip_shodan/network_public_ip_shodan.py
> +                                f"Elastic IP {ip.ip_address} is not listed in Shodan."
Done

2024-02-26 11:45 UTC, pedrooot commented
No merge until https://github.com/prowler-cloud/prowler/pull/3432 is merged

2024-02-27 12:10 UTC, sergargar approved these changes

2024-02-27 12:33 UTC, merged