Make 3.x tests simpler and more useful
toniblyx/prowler pull request #366
Opened 2019-08-16 10:06 UTC by mastertinner

This makes the 3.x tests not rely on the user naming their alarms in a certain way (which is not even provided by the CIS whitepaper so it's hard to get the names right). Furthermore, it makes the code much more maintainable and streamlined. As a third advantage, it makes the checks output more user friendly and unified across all 3.x checks.

2019-08-16 11:46 UTC, mastertinner commented
Should fix #358

2019-08-17 04:29 UTC, toniblyx requested changes
This is a great improvement @mastertinner, and has been a pain for long, thanks! I think it is better if we move `check3x` function file into the `includes` folder to make it more consistent with other functions and leave `checks` folder for checks only. 

it has to be added a line to `prowler` file like this:
`. $PROWLER_DIR/include/check3x`

What do you think, does it make sense? 

Thanks again.

2019-08-17 10:12 UTC, mastertinner commented
Thanks for your feedback, @toniblyx. What you wrote makes sense. I changed the files accordingly and rebased on the latest `master` branch.

2019-08-17 11:44 UTC, toniblyx requested changes
Thanks @mastertinner, sorry to bother again, I didn't explain myself very good before, I meant to add `. "$PROWLER_DIR/include/check3x"` into the actual `prowler` file just once instead of adding it in every single check, it is just cleaner to add it into here fore example: 
https://github.com/toniblyx/prowler/blob/master/prowler#L168

2019-08-17 18:07 UTC, mastertinner commented
Done :)

2019-08-18 06:03 UTC, toniblyx approved these changes
Amazing work @mastertinner, thank you very much, I hope users can take advantage of it pretty soon!

2019-08-18 06:03 UTC, merged

2019-08-18 07:56 UTC, mastertinner commented
Great. Thanks for all your feedback and for responding so quickly!