docs(devel-guide): Add provider section and remove audit_info section
toniblyx/prowler pull request #3756
Opened 2024-04-11 12:30 UTC by puchy22

### Context

The audit_info is no longer used in v4, change it for service section.

### Description

Remove the old `audit_info.md, add new `provider.md, changes in the nav bar and fix links from services adding the new k8s service.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-04-11 12:38 UTC, pedrooot requested changes
Nice job! @puchy22 Please, review my comments.

2024-04-11 12:38 UTC, pedrooot commented on docs/developer-guide/provider.md
> +To create a new provider that is not supported now by Prowler and add your security checks must create a new folder where store all related with it (services, checks, etc.). It must be store in route
```suggestion
To create a new provider that is not supported now by Prowler and add your security checks must create a new folder where store all related with it (services, checks, etc.). It must be stored in `prowler/providers/<new_provider_name>/`.
```

2024-04-11 12:38 UTC, pedrooot commented on docs/developer-guide/provider.md
> +The Prowler's provider structure is the following and the way to use it is just in the generic service of each provider passing as a parameter of constructor to initialize all necessary session value
```suggestion
The structure for Prowler's providers is set up in such a way that they can be utilized through a generic service specific to each provider. This is achieved by passing the required parameters to the constructor, which in turn initializes all the necessary session values.
```

2024-04-11 12:38 UTC, pedrooot commented on docs/developer-guide/provider.md
> +Due to the complexity and differencies of each provider use the rest of the providers as a template for the implementation.
```suggestion
Due to the complexity and differences of each provider use the rest of the providers as a template for the implementation.
```

2024-04-11 13:07 UTC, jfagoagas requested changes
Great work @puchy22 !! Please review my comments when you get a chance. Thanks!

2024-04-11 13:07 UTC, jfagoagas commented on docs/developer-guide/provider.md
> +Providers are the foundation on which Prowler is built, a simple definition for a cloud provider could be "third-party company that offers a platform where any IT resource you need is available at an
```suggestion
Providers are the foundation on which Prowler is built, a simple definition for a cloud provider could be "third-party company that offers a platform where any IT resource you need is available at any time upon request". The most well-known cloud providers are Amazon Web Services, Azure from Microsoft and Google Cloud which are already supported by Prowler.
```

2024-04-11 13:07 UTC, jfagoagas commented on docs/developer-guide/provider.md
> +To create a new provider that is not supported now by Prowler and add your security checks must create a new folder where store all related with it (services, checks, etc.). It must be store in route
```suggestion
To create a new provider that is not supported now by Prowler and add your security checks you must create a new folder to store all the related files within it (services, checks, etc.). It must be store in route `prowler/providers/<new_provider_name>/`.
```

2024-04-11 13:07 UTC, jfagoagas commented on docs/developer-guide/provider.md
> +All the providers in Prowler inherits from the same [base class](https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/common/provider.py). It is an [abstract base class](https://doc
```suggestion
All the providers in Prowler inherits from the same [base class](https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/common/provider.py). It is an [abstract base class](https://docs.python.org/3/library/abc.html) that defines the interface for all provider classes.
```

2024-04-11 13:07 UTC, jfagoagas commented on docs/developer-guide/provider.md
> +All the providers in Prowler inherits from the same [base class](https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/common/provider.py). It is an [abstract base class](https://doc
Here I'd explain the characteristics of the provider base class and explain what methods are enforced, also you can include a generic provider in pseudo-code to explain that first we need to gather arguments, then setup authentication, load the config, etc.

2024-04-15 09:21 UTC, jfagoagas commented on docs/developer-guide/provider.md
> +To facilitate understanding here is a pseudocode of how could be the most basic provider could be with examples.
```suggestion
To facilitate understanding here is a pseudocode of how the most basic provider could be with examples.
```

2024-04-15 09:24 UTC, jfagoagas approved these changes
Awesome @puchy22, this is a great improvement in our Developer Guide, thanks for taking care of this 👏

2024-04-15 09:36 UTC, pedrooot approved these changes
🔝 🔝 🔝  Nice job @puchy22

2024-04-15 11:12 UTC, merged