fix(aws): not show findings when AccessDenieds
toniblyx/prowler pull request #3803
Opened 2024-04-17 09:19 UTC by sergargar

### Context

Please include relevant motivation and context for this PR.

### Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-04-17 09:57 UTC, sergargar commented
We need to cover the case when there is a region denied and other accessible.

2024-04-19 07:08 UTC, jfagoagas requested changes
That's a great work and improvement @sergargar 👏 

Please, document the criteria followed in the services and how this needs to be done in the checks, include all in the developer guide since it's an important change.

It'd be super helpful to complete tests cases and cover this, you can use `mock_object.side_effect = ClientError(error_response, operation_name)` to raise exceptions like if boto3 does that.

Thanks!

2024-04-19 07:08 UTC, jfagoagas commented on prowler/providers/aws/services/account/account_maintain_different_contact_details_to_security_billing_and_operations/account_maintain_different_contact_details_to_security_billing_and_operations.py
> +        return []
Please do this as we do in the rest of checks with `findings = []` and then`findings.append(report)`. The return should be `return findings`

2024-04-19 07:08 UTC, jfagoagas commented on prowler/providers/aws/services/backup/backup_service.py
> +                            self.backup_vaults = []
It is important to leave this documented somewhere for the next people using this code:
- If object is None we set it as empty list
- If the operation raises an exception we set the object as None

2024-04-19 07:08 UTC, jfagoagas commented on prowler/providers/aws/services/backup/backup_service.py
> +                            self.backup_vaults = []
Also we need to test all these cases to know if they are working fine.

2024-04-19 07:08 UTC, jfagoagas commented on prowler/providers/aws/services/backup/backup_vaults_exist/backup_vaults_exist.py
> +        if backup_client.backup_vaults is not None:
Why here you are checking against `is not None` and in the above check you just check if the object has something?

2024-04-19 07:08 UTC, jfagoagas commented on prowler/providers/aws/services/cloudtrail/cloudtrail_service.py
> +                    if self.trails is None:
How is this going to be none if this is always an empty map at first? See line 18.

2024-04-19 07:08 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_changes_to_network_acls_alarm_configured/cloudwatch_changes_to_network_acls_alarm_configured.py
> +        try:
Why is this here?

2024-04-19 07:08 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_changes_to_network_acls_alarm_configured/cloudwatch_changes_to_network_acls_alarm_configured.py
> +            return findings
The same here.

2024-04-19 07:08 UTC, jfagoagas commented on prowler/providers/aws/services/cloudwatch/cloudwatch_service.py
> +                        if self.metric_alarms is None:
Again, how is this going to be None? I think I'm missing something in this PR...

2024-04-19 07:08 UTC, jfagoagas commented on prowler/providers/aws/services/iam/iam_securityaudit_role_created/iam_securityaudit_role_created.py
> +            if iam_client.entities_role_attached_to_securityaudit_policy:
Could you complete this condition to be more readable? Is this checking if `True`, a list with values?

2024-04-19 07:08 UTC, jfagoagas commented on prowler/providers/aws/services/iam/iam_support_role_created/iam_support_role_created.py
> +            if iam_client.entities_role_attached_to_support_policy:
Could you complete this condition to be more readable? Is this checking if True, a list with values?

2024-04-22 08:22 UTC, sergargar commented on prowler/providers/aws/services/iam/iam_securityaudit_role_created/iam_securityaudit_role_created.py
> +            if iam_client.entities_role_attached_to_securityaudit_policy:
It is the same condition as we had, it is checking if the list is not empty.

2024-04-22 08:23 UTC, MrCloudSec commented on prowler/providers/aws/services/iam/iam_support_role_created/iam_support_role_created.py
> +            if iam_client.entities_role_attached_to_support_policy:
It is the same condition as we had, it is checking if the list is not empty.

2024-04-22 08:30 UTC, sergargar commented on prowler/providers/aws/services/cloudtrail/cloudtrail_service.py
> +                    if self.trails is None:
It would be None in the cases where a previous region gives us an AccessDenied.

2024-04-22 08:31 UTC, sergargar commented on prowler/providers/aws/services/cloudwatch/cloudwatch_service.py
> +                        if self.metric_alarms is None:
It would be None in the cases where a previous region gives us an AccessDenied.

2024-04-22 08:32 UTC, sergargar commented on prowler/providers/aws/services/backup/backup_vaults_exist/backup_vaults_exist.py
> +        if backup_client.backup_vaults is not None:
What above check are you talking about?

2024-04-22 08:33 UTC, sergargar commented
@jfagoagas re-review it whenever you get a chance, please! Only the tests and docs are pending.

2024-04-22 11:19 UTC, jfagoagas commented on prowler/providers/aws/services/backup/backup_vaults_exist/backup_vaults_exist.py
> +        if backup_client.backup_vaults is not None:
solved, just checking if empty or access denied.

2024-04-22 13:34 UTC, sergargar commented
Pending testing for CloudTrail, CloudWatch and IAM.

2024-04-29 10:24 UTC, sergargar commented
Pending testing for CloudTrail and CloudWatch.

2024-04-29 10:59 UTC, sergargar commented
Pending testing for CloudWatch.

2024-04-29 15:42 UTC, jfagoagas approved these changes

2024-04-29 15:42 UTC, merged