chore(mitre gcp): add mitre mapping for gcp
toniblyx/prowler pull request #3899
Opened 2024-04-30 07:43 UTC by n4ch04

### Context

We need to cover mitre attack mapping for gcp

### Description

Include mitre attack mapping for gcp

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-04-30 13:01 UTC, pedrooot requested changes
Great work! @n4ch04 Please review my comments 🙏🏼

2024-04-30 13:01 UTC, pedrooot commented on prowler/lib/outputs/file_descriptors.py
> +                                MitreAttackAWS,
`elif provider.type == "azure":` appears two times in this method, could you please unify them?

2024-04-30 13:48 UTC, pedrooot commented on prowler/compliance/azure/mitre_attack_azure.json
> +        "networkfirewall_in_all_vpc"
```suggestion
```
"networkfirewall_in_all_vpc" is not a check for azure

2024-05-03 05:50 UTC, n4ch04 commented on prowler/compliance/azure/mitre_attack_azure.json
> +        "networkfirewall_in_all_vpc"
Deleted

2024-05-03 06:16 UTC, n4ch04 commented on prowler/lib/outputs/file_descriptors.py
> +                                MitreAttackAWS,
Solved

2024-05-03 10:29 UTC, pedrooot approved these changes, later dismissed
🔝  work @n4ch04

2024-05-03 11:28 UTC, MrCloudSec commented on prowler/compliance/gcp/cis_2.0_gcp.json
> +      "Checks": [],
```suggestion
      "Checks": [
        "iam_cloud_asset_inventory_enabled"
      ],
```

2024-05-03 11:30 UTC, sergargar approved these changes, later dismissed

2024-05-06 08:39 UTC, sergargar approved these changes

2024-05-06 09:10 UTC, merged