feat(rds): Add RDS certificate expiration check
toniblyx/prowler pull request #4002
Opened 2024-05-14 17:44 UTC by madereddy

### Context

Ensure that the SSL/TLS certificates configured for your Amazon RDS are not expired.

### Description

Check RDS certificate validity and inform if the certificate will expire soon. Certificate rotation takes coordination between the application and RDS. 

For default RDS Cert and customer override RDS Cert with an expiration greater than 3 months will PASS.

For default RDS Cert and customer override RDS Cert with less than 3 months it will FAIL with a severity of medium.

For default RDS Cert and customer override RDS Cert that are expired it will FAIL with a severity of critical.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-05-15 01:47 UTC, madereddy commented
Competing with https://github.com/prowler-cloud/prowler/pull/4003 and https://github.com/prowler-cloud/prowler/pull/4004

Recommended to merge this one first as it is an additional check.

2024-05-15 08:26 UTC, sergargar commented on prowler/providers/aws/services/rds/rds_instance_certificate_expiration/rds_instance_certificate_expiration.py
> +                    print(valid_till)
```suggestion
```

2024-05-15 08:29 UTC, sergargar commented on prowler/providers/aws/services/rds/rds_service.py
> +                                    ca_cert=instance.get("CACertificateIdentifier"),
```suggestion
                                    ca_cert=instance.get("CACertificateIdentifier", []),
```

2024-05-15 08:30 UTC, sergargar commented on prowler/providers/aws/services/rds/rds_service.py
> +                    for certificate in instance.ca_cert:
Is not `ca_cert` a String?

2024-05-15 08:32 UTC, MrCloudSec commented on prowler/providers/aws/services/rds/rds_instance_certificate_expiration/rds_instance_certificate_expiration.py
> +            report.severity = "critical"
Instead of `report.severity`, you have to use `report.check_metadata.Severity`.

2024-05-15 08:33 UTC, MrCloudSec requested changes
Thanks for the PR @madereddy, I like this check! Please, review my comments 😄

2024-05-15 12:47 UTC, madereddy commented on prowler/providers/aws/services/rds/rds_instance_certificate_expiration/rds_instance_certificate_expiration.py
> +                    print(valid_till)
Removed in latest commit

2024-05-15 12:47 UTC, madereddy commented on prowler/providers/aws/services/rds/rds_service.py
> +                    for certificate in instance.ca_cert:
Removed in latest commit

2024-05-15 12:48 UTC, madereddy commented on prowler/providers/aws/services/rds/rds_instance_certificate_expiration/rds_instance_certificate_expiration.py
> +            report.severity = "critical"
Corrected in the check and the tests as well.

2024-05-15 13:28 UTC, madereddy commented
Not sure why pr-lint-test 3.9 failed. I ran the test several times on my machine and it was successful.

```
prowler-py3.10) # pytest -n auto -vvv -s -x tests/providers/aws/services/rds/rds_instance_no_public_access
================================================================= test session starts =================================================================
platform linux -- Python 3.10.12, pytest-8.2.0, pluggy-1.5.0 -- /root/.cache/pypoetry/virtualenvs/prowler-_7q4EYpC-py3.10/bin/python
cachedir: .pytest_cache
Using --randomly-seed=2455016802
rootdir: /config/data/prowler
configfile: pyproject.toml
plugins: anyio-4.3.0, dash-2.17.0, cov-5.0.0, env-1.1.3, randomly-3.15.0, xdist-3.6.1
4 workers [5 items]     
scheduling tests via LoadScheduling

tests/providers/aws/services/rds/rds_instance_no_public_access/rds_instance_no_public_access_test.py::Test_rds_instance_no_public_access::test_rds_instance_public_with_public_sg 
tests/providers/aws/services/rds/rds_instance_no_public_access/rds_instance_no_public_access_test.py::Test_rds_instance_no_public_access::test_rds_instance_public_with_filtered_sg 
tests/providers/aws/services/rds/rds_instance_no_public_access/rds_instance_no_public_access_test.py::Test_rds_instance_no_public_access::test_rds_instance_public 
tests/providers/aws/services/rds/rds_instance_no_public_access/rds_instance_no_public_access_test.py::Test_rds_instance_no_public_access::test_rds_instance_private 
[gw3] PASSED tests/providers/aws/services/rds/rds_instance_no_public_access/rds_instance_no_public_access_test.py::Test_rds_instance_no_public_access::test_rds_instance_public 
[gw0] PASSED tests/providers/aws/services/rds/rds_instance_no_public_access/rds_instance_no_public_access_test.py::Test_rds_instance_no_public_access::test_rds_instance_private 
[gw2] PASSED tests/providers/aws/services/rds/rds_instance_no_public_access/rds_instance_no_public_access_test.py::Test_rds_instance_no_public_access::test_rds_instance_public_with_filtered_sg 
[gw1] PASSED tests/providers/aws/services/rds/rds_instance_no_public_access/rds_instance_no_public_access_test.py::Test_rds_instance_no_public_access::test_rds_instance_public_with_public_sg 
tests/providers/aws/services/rds/rds_instance_no_public_access/rds_instance_no_public_access_test.py::Test_rds_instance_no_public_access::test_rds_no_instances 
[gw1] PASSED tests/providers/aws/services/rds/rds_instance_no_public_access/rds_instance_no_public_access_test.py::Test_rds_instance_no_public_access::test_rds_no_instances 

================================================================= 5 passed in 15.72s ==================================================================
```

2024-05-15 17:53 UTC, madereddy commented
Reviewed further, sync master branch back into my fork and then rebased this commit in and the PR Lint 3.9 succeeded. 
https://github.com/madereddy/prowler/actions/runs/9100128819/job/25014246558

```
============================= test session starts ==============================
platform linux -- Python 3.9.19, pytest-8.2.0, pluggy-1.5.0
Using --randomly-seed=4172765213
rootdir: /home/runner/work/prowler/prowler
configfile: pyproject.toml
plugins: anyio-4.3.0, randomly-3.15.0, env-1.1.3, dash-2.17.0, cov-5.0.0, xdist-3.6.1
created: 4/4 workers
4 workers [3167 items]
........................................................................ [  2%]
........................................................................ [  4%]
........................................................................ [  6%]
........................................................................ [  9%]
........................................................................ [ 11%]
........................................................................ [ 13%]
........................................................................ [ 15%]
........................................................................ [ 18%]
........................................................................ [ 20%]
........................................................................ [ 22%]
........................................................................ [ 25%]
........................................................................ [ 27%]
........................................................................ [ 29%]
........................................................................ [ 31%]
........................................................................ [ 34%]
........................................................................ [ 36%]
........................................................................ [ 38%]
........................................................................ [ 40%]
........................................................................ [ 43%]
........................................................................ [ 45%]
........................................................................ [ 47%]
........................................................................ [ 50%]
........................................................................ [ 52%]
........................................................................ [ 54%]
........................................................................ [ 56%]
........................................................................ [ 59%]
........................................................................ [ 61%]
........................................................................ [ 63%]
........................................................................ [ 65%]
........................................................................ [ 68%]
........................................................................ [ 70%]
........................................................................ [ 72%]
........................................................................ [ 75%]
........................................................................ [ 77%]
........................................................................ [ 79%]
........................................................................ [ 81%]
........................................................................ [ 84%]
........................................................................ [ 86%]
........................................................................ [ 88%]
........................................................................ [ 90%]
........................................................................ [ 93%]
........................................................................ [ 95%]
........................................................................ [ 97%]
.......................................................................  [100%]
=============================== warnings summary ===============================
tests/providers/azure/services/defender/defender_auto_provisioning_log_analytics_agent_vms_on/defender_auto_provisioning_log_analytics_agent_vms_on_test.py::Test_defender_auto_provisioning_log_analytics_agent_vms_on::test_defender_auto_provisioning_log_analytics_on
  /home/runner/.cache/pypoetry/virtualenvs/prowler-MpuilnhB-py3.9/lib/python3.9/site-packages/azure/mgmt/security/v2023_01_01/models/_models_py3.py:91: DeprecationWarning: invalid escape sequence \ 
    """A plan's extension properties.
tests/providers/azure/services/defender/defender_auto_provisioning_log_analytics_agent_vms_on/defender_auto_provisioning_log_analytics_agent_vms_on_test.py::Test_defender_auto_provisioning_log_analytics_agent_vms_on::test_defender_auto_provisioning_log_analytics_on
  /home/runner/.cache/pypoetry/virtualenvs/prowler-MpuilnhB-py3.9/lib/python3.9/site-packages/azure/mgmt/security/v2023_01_01/models/_models_py3.py:144: DeprecationWarning: invalid escape sequence \ 
    """
tests/providers/azure/services/defender/defender_auto_provisioning_log_analytics_agent_vms_on/defender_auto_provisioning_log_analytics_agent_vms_on_test.py::Test_defender_auto_provisioning_log_analytics_agent_vms_on::test_defender_auto_provisioning_log_analytics_on
  /home/runner/.cache/pypoetry/virtualenvs/prowler-MpuilnhB-py3.9/lib/python3.9/site-packages/azure/mgmt/security/v2023_01_01/models/_models_py3.py:236: DeprecationWarning: invalid escape sequence \ 
    """Microsoft Defender for Cloud is provided in two pricing tiers: free and standard. The standard
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
---------- coverage: platform linux, python 3.9.19-final-0 -----------
Coverage XML written to file coverage.xml
================= 3167 passed, 3 warnings in 886.53s (0:14:46) =================
```

2024-05-18 11:15 UTC, madereddy commented
@sergargar @jfagoagas Can you rerun the failed lint test?

2024-05-20 13:30 UTC, madereddy commented
> ## [Codecov](https://app.codecov.io/gh/prowler-cloud/prowler/pull/4002?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=prowler-cloud) Report
> 
> Attention: Patch coverage is `96.96970%` with `2 lines` in your changes are missing coverage. Please review.
> 
> > Project coverage is 86.50%. Comparing base [(`45ccd7e`)](https://app.codecov.io/gh/prowler-cloud/prowler/commit/45ccd7e79302ac367d32d75ca2a2b4eb2a6dfe80?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=prowler-cloud) to head [(`7e391db`)](https://app.codecov.io/gh/prowler-cloud/prowler/pull/4002?dropdown=coverage&src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=prowler-cloud).
> > Report is 17 commits behind head on master.
> 
> [Files](https://app.codecov.io/gh/prowler-cloud/prowler/pull/4002?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=prowler-cloud) 	Patch % 	Lines
> [prowler/providers/aws/services/rds/rds_service.py](https://app.codecov.io/gh/prowler-cloud/prowler/pull/4002?src=pr&el=tree&filepath=prowler%2Fproviders%2Faws%2Fservices%2Frds%2Frds_service.py&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=prowler-cloud#diff-cHJvd2xlci9wcm92aWRlcnMvYXdzL3NlcnZpY2VzL3Jkcy9yZHNfc2VydmljZS5weQ==) 	85.71% 	[2 Missing ⚠️ ](https://app.codecov.io/gh/prowler-cloud/prowler/pull/4002?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=prowler-cloud)
> Additional details and impacted files
> 
> [☔ View full report in Codecov by Sentry](https://app.codecov.io/gh/prowler-cloud/prowler/pull/4002?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=prowler-cloud). 📢 Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=prowler-cloud).

Looking at the codecov report, I see that changes I made have more coverage, but indirectly the ec2 service is going down by about 5.47%. Is there anything I need to do to fix this?

2024-05-20 13:46 UTC, sergargar commented
Hi @madereddy , I have added the case of RDS Certificates that expires in less than a month the check will FAIL with a severity of high.

2024-05-20 13:47 UTC, sergargar approved these changes, later dismissed

2024-05-20 14:20 UTC, sergargar approved these changes

2024-05-20 14:41 UTC, merged