refactor(SecurityHub): create class
toniblyx/prowler pull request #4133
Opened 2024-05-30 07:47 UTC by jfagoagas

### Context

We want to move the outputs to a decoupled component.

### Description

Create the SecurityHub class and update code accordingly.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-03 13:40 UTC, pedrooot reviewed
Please, review my comments. Thanks!

2024-06-03 13:40 UTC, pedrooot commented on tests/providers/aws/utils.py
> +    if hasattr(input_arguments, "status") and input_arguments.status:
```suggestion
    if getattr(input_arguments, 'status', None):
```

2024-06-03 13:40 UTC, pedrooot commented on tests/providers/aws/utils.py
> +        and input_arguments.send_sh_only_fails
```suggestion
        getattr(input_arguments, 'send_sh_only_fails', None)
```

2024-06-04 12:36 UTC, jfagoagas commented on prowler/lib/outputs/security_hub/security_hub.py
> +                success_count = self.__send_findings_to_security_hub__(
```suggestion
                success_count += self.__send_findings_to_security_hub__(
```

2024-06-04 12:56 UTC, jfagoagas commented on tests/providers/aws/utils.py
> +    if hasattr(input_arguments, "status") and input_arguments.status:
Great one!

2024-06-04 12:57 UTC, jfagoagas commented on tests/providers/aws/utils.py
> +        and input_arguments.send_sh_only_fails
Great one!

2024-06-04 13:36 UTC, pedrooot submitted a review, later dismissed
LGTM!!

2024-06-04 15:10 UTC, sergargar requested changes
Love it! Please, check my comments.

2024-06-04 15:10 UTC, MrCloudSec commented on prowler/lib/outputs/security_hub/security_hub.py
> +    def prepare_security_hub_findings(
```suggestion
    def prepare(
```

2024-06-04 15:10 UTC, MrCloudSec commented on prowler/lib/outputs/security_hub/security_hub.py
> +    def verify_security_hub_integration_enabled_per_region(
```suggestion
    def verify(
```

2024-06-04 15:10 UTC, MrCloudSec commented on prowler/lib/outputs/security_hub/security_hub.py
> +    def resolve_security_hub_previous_findings(
```suggestion
    def resolve(
```

2024-06-04 15:10 UTC, sergargar commented on prowler/lib/outputs/security_hub/security_hub.py
> +    def batch_send_to_security_hub(
```suggestion
    def send(
```

2024-06-04 15:10 UTC, sergargar commented on prowler/lib/outputs/security_hub/security_hub.py
> +    def __send_findings_to_security_hub__(
```suggestion
    def __batch_import_findings__(
```

2024-06-04 15:10 UTC, sergargar commented on prowler/lib/outputs/security_hub/security_hub.py
> +        security_hub_findings_per_region: dict,
Why not getting it from the class attribute?

2024-06-04 15:38 UTC, sergargar commented on prowler/lib/outputs/security_hub/security_hub.py
> +        security_hub_findings_per_region: dict,
We will do it in the future.

2024-07-08 12:00 UTC, jfagoagas commented
Closed in favor of https://github.com/prowler-cloud/prowler/pull/4397.

2024-07-08 12:00 UTC, closed without merging