feat(RDS): Additional RDS checks
toniblyx/prowler pull request #4233
Opened 2024-06-11 02:49 UTC by sansns

### Context

1. Add default admin user check.
2. Backtrack is enabled on Aurora MySQL Clusters
3. IAM Authentication is enabled for DB Instances/Clusters
4. Snapshots are encrypted

### Description

1. 
```
All RDS DB instances/clusters use ```admin``` as a default username other than PostgreSQL based instances/clusters which use ```postgres``` as the default user. Added checks to find both ```admin``` and ```postgres``` being the default admin username. 

Trend Cloud Conformity and AWS RDS Controls only check for ```admin```, but I also added ```postgres``` as that is the default PostgreSQL username to the check are more robust.

https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/RDS/rds-master-username.html#
https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html#rds-25
```
2. 
```
Ensure that the Backtrack feature is enabled for your Amazon Aurora (with MySQL compatibility) database clusters in order to backtrack your clusters to a specific time, without using backups. Backtrack is an Amazon RDS feature that allows you to specify the amount of time that an Aurora MySQL database cluster needs to retain change records, in order to have a fast way to recover from user errors, such as dropping the wrong table or deleting the wrong row by moving your MySQL database to a prior point in time without the need to restore from a recent backup.

Trend Cloud Conformity has it as a low priority
AWS RDS Controls has it as medium priority

DB Clusters
https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/RDS/backtrack.html#
https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html#rds-14
https://docs.aws.amazon.com/config/latest/developerguide/aurora-mysql-backtracking-enabled.html
```
3.
 ```
With this feature enabled, you don't have to use a password when you connect to your MySQL/PostgreSQL database, instead you can use an authentication token. An authentication token is a unique string of characters with a lifetime of 15 minutes that Amazon RDS generates on your request. IAM Database Authentication removes the need of storing user credentials within the database configuration, because authentication is managed externally using Amazon IAM.

DB Instances
https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/RDS/iam-database-authentication.html#
https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html#rds-10

DB Clusters
https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html#rds-12
```
4.
```
Ensure that your manual Amazon RDS database snapshots are encrypted in order to achieve compliance for data-at-rest encryption within your organization. The Amazon RDS snapshot encryption and decryption process is handled transparently and does not require any additional action from you or your application. 

https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/RDS/snapshot-encrypted.html#
https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html#rds-4
```

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-12 06:34 UTC, snaow commented
Thanks @sansns! We will review and merge/get back to you soon

2024-06-20 16:00 UTC, sergargar requested changes

2024-06-20 16:00 UTC, MrCloudSec commented on prowler/providers/aws/services/rds/rds_cluster_backtrack_enabled/rds_cluster_backtrack_enabled.metadata.json
> +      "Terraform": "https://docs.prowler.com/checks/aws/general-policies/ensure-that-rds-instances-have-backup-policy#terraform"
```suggestion
      "Terraform": "https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/RDS/backtrack.html#"
```

2024-06-20 16:00 UTC, MrCloudSec commented on prowler/providers/aws/services/rds/rds_cluster_backtrack_enabled/rds_cluster_backtrack_enabled.metadata.json
> +  "Risk": "Once the Backtrack feature is enabled, Amazon RDS can quickly \"rewind\" your Aurora MySQL database cluster to a point in time that you specify. In contrast to the backup and restore metho
```suggestion
  "Risk": "Once the Backtrack feature is enabled, Amazon RDS can quickly 'rewind' your Aurora MySQL database cluster to a point in time that you specify. In contrast to the backup and restore method, with Backtrack you can easily undo a destructive action, such as a DELETE query without a WHERE clause, with minimal downtime, you can rewind your Aurora cluster in just few minutes, and you can repeatedly backtrack a database cluster back and forth in time to help determine when a particular data change occurred.",
```

2024-06-20 16:00 UTC, MrCloudSec commented on prowler/providers/aws/services/rds/rds_instance_default_admin/rds_instance_default_admin.py
> +            # Check only RDS DB instances that support parameter group encryption
```suggestion
            # Check only RDS DB instances that are not clustered
```

2024-06-20 16:00 UTC, MrCloudSec commented on prowler/providers/aws/services/rds/rds_instance_default_admin/rds_instance_default_admin.py
> +            # Check RDS Clusters that support TLS encryption
```suggestion
```

2024-06-20 16:00 UTC, MrCloudSec commented on prowler/providers/aws/services/rds/rds_service.py
> +                                    ],
```suggestion
                                    iam_auth=instance.get(
                                        "IAMDatabaseAuthenticationEnabled", False
                                    ),
```

2024-06-20 16:00 UTC, MrCloudSec commented on prowler/providers/aws/services/rds/rds_service.py
> +                                        ],
```suggestion
                                        iam_auth=cluster.get(
                                            "IAMDatabaseAuthenticationEnabled", False
                                        ),
```

2024-06-20 16:00 UTC, MrCloudSec commented on prowler/providers/aws/services/rds/rds_service.py
> +    iam_auth: Optional[bool]
```suggestion
    username: str
    iam_auth: bool
```

2024-06-20 16:00 UTC, MrCloudSec commented on prowler/providers/aws/services/rds/rds_service.py
> +    iam_auth: Optional[bool]
```suggestion
    username: str
    iam_auth: bool
```

2024-06-20 16:00 UTC, MrCloudSec commented on prowler/providers/aws/services/rds/rds_service.py
> +    backtrack: int = 0
```suggestion
    backtrack: int
```

2024-06-20 16:23 UTC, sergargar approved these changes
These checks are awesome, thanks @sansns !

2024-06-20 17:41 UTC, merged