feat(DocumentDB): New DocumentDB checks
toniblyx/prowler pull request #4247
Opened 2024-06-13 02:26 UTC by sansns

### Context
New Checks
1. Backup enabled
2. Cloudwatch Log Export for Profiler and Audit checks
3. Deletion Protection enabled

Modified Checks
1. Changed DocumentDB Instance storage encrypted check to check the Clusters storage encryption. 

### Description

Trend Conformity: https://www.trendmicro.com/cloudoneconformity-staging/knowledge-base/aws/DocumentDB/
AWS Security Hub: https://docs.aws.amazon.com/securityhub/latest/userguide/documentdb-controls.html

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-20 17:38 UTC, sergargar commented on prowler/providers/aws/services/documentdb/documentdb_cluster_storage_encrypted/documentdb_cluster_storage_encrypted.metadata.json
> +      "Terraform": "https://www.trendmicro.com/cloudoneconformity-staging/knowledge-base/aws/DocumentDB/encryption-enabled.html#"
```suggestion
      "Terraform": "https://docs.prowler.com/checks/aws/general-policies/bc_aws_general_28/"
```

2024-06-20 17:38 UTC, sergargar commented on prowler/providers/aws/services/documentdb/documentdb_cluster_storage_encrypted/documentdb_cluster_storage_encrypted.metadata.json
> +      "CLI": "https://www.trendmicro.com/cloudoneconformity-staging/knowledge-base/aws/DocumentDB/encryption-enabled.html#",
```suggestion
      "CLI": "https://docs.prowler.com/checks/aws/general-policies/bc_aws_general_28/",
```

2024-06-20 17:39 UTC, sergargar commented on prowler/providers/aws/services/documentdb/documentdb_cluster_cloudwatch_log_export/documentdb_cluster_cloudwatch_log_export.metadata.json
> +  "CheckID": "documentdb_cluster_c_log_export",
```suggestion
  "CheckID": "documentdb_cluster_cloudwatch_log_export",
```

2024-06-20 17:40 UTC, sergargar commented on prowler/providers/aws/services/documentdb/documentdb_cluster_backup_enabled/documentdb_cluster_backup_enabled.py
> +                and cluster.backup_retention_period < 7
Could you put this as a configurable variable, please?

2024-06-20 17:40 UTC, sergargar requested changes
Thank you @sansns ! Please, check my comments.

2024-06-24 14:17 UTC, sansns commented
Addressed all the comments.

2024-06-24 15:40 UTC, sergargar approved these changes

2024-06-24 15:40 UTC, merged