feat(s3): reduce false positive in s3 public check
toniblyx/prowler pull request #4281
Opened 2024-06-20 10:36 UTC by puchy22

### Context

Context in Issue #4257 

Not checking conditions in policy statements

### Description

Add new policy function to check policy conditions and improve checks using this functions. Everything added have been tested properly.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-20 13:19 UTC, sergargar submitted a review, later dismissed
LGTM, love this fix!

2024-06-20 13:58 UTC, jmanduca-psfy commented
Just tried it out, it works for some bucket policies but not others - this looks like it is due to the case of your `no_public_conditions`, as the value in policy is not case-sensitive, causing some that were manually created to fail. 
Fail: 
`            "Condition": {
                "StringEquals": {
                    "aws:sourcevpc": "vpc-12334"`
Pass:
`            "Condition": {
                "StringEquals": {
                    "aws:SourceVpc": "vpc-12334"`

2024-06-20 14:08 UTC, jfagoagas commented
> Just tried it out, it works for some bucket policies but not others - this looks like it is due to the case of your `no_public_conditions`, as the value in policy is not case-sensitive, causing some that were manually created to fail. Fail: ` "Condition": { "StringEquals": { "aws:sourcevpc": "vpc-12334"` Pass: ` "Condition": { "StringEquals": { "aws:SourceVpc": "vpc-12334"`

Great catch, we need to do the match that way, please @puchy22 change it and add some tests to cover that.

2024-06-20 14:09 UTC, jfagoagas requested changes
See above comment and check the function `is_condition_block_restrictive` at https://github.com/prowler-cloud/prowler/blob/9fbd627f9aec3edee4f7ddc25849faa11db6187e/prowler/providers/aws/lib/policy_condition_parser/policy_condition_parser.py

We should unify both functions since they are similar.

2024-06-20 17:10 UTC, sergargar commented
@puchy22 where did you get the `no_public_conditions` from?

2024-06-24 16:29 UTC, sergargar commented on prowler/providers/aws/services/iam/lib/policy.py
> +def check_full_service_access(service: str, policy: dict) -> bool:
Is this function being used?

2024-06-25 07:09 UTC, jfagoagas requested changes

2024-06-25 07:09 UTC, jfagoagas commented on prowler/providers/aws/services/iam/lib/policy.py
> +                    condition_statement["IpAddress"]["aws:sourceip"]
Could you define the following as constants?
- `aws:sourceip`
- `IpAddress`

2024-06-25 07:09 UTC, jfagoagas commented on prowler/providers/aws/services/iam/lib/policy.py
> +    is_from_private_ip = False
Could you add a try/except block for the whole function?

2024-06-25 07:09 UTC, jfagoagas commented on prowler/providers/aws/services/iam/lib/policy.py
> +                            break
Cover this line with a test please.

2024-06-25 07:09 UTC, jfagoagas commented on prowler/providers/aws/services/iam/lib/policy.py
> +                    logger.error(f"Invalid IP: {ip}")
Cover this line with a test please.

2024-06-25 07:09 UTC, jfagoagas commented on prowler/providers/aws/services/s3/s3_bucket_public_access/s3_bucket_public_access.py
> +                                        principals = (
Cover this line with a test please.

2024-06-25 07:09 UTC, jfagoagas commented on prowler/providers/aws/services/iam/lib/policy.py
> +    if condition_statement.get("IpAddress", {}):
I will move this line into the function caller, makes little sense to call the function if the condition is not `IpAddress`.

2024-06-25 07:09 UTC, jfagoagas commented on tests/providers/aws/services/iam/lib/policy_test.py
> +        assert not check_full_service_access("s3", policy4)
Could you please create one test case for each policy? It's simpler to work with the tests are failing.

2024-06-25 08:28 UTC, jfagoagas approved these changes
This PR is pure gold 🏅 Thanks for the effort!!

2024-06-25 12:55 UTC, sergargar approved these changes
🤩

2024-06-25 12:55 UTC, merged