Add error checking to checks extra77 and extra765
toniblyx/prowler pull request #443
Opened 2019-12-26 19:57 UTC by zfLQ2qx2

Check extra765 - Add additional error checking, a recent awscli is required to run this check successfully.

Check extra77 - Add additional error checking, use jq for policy parsing instead of awk

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2019-12-26 19:57 UTC, zfLQ2qx2 commented
@toniblyx I've raised a pull request

2019-12-27 15:33 UTC, toniblyx requested changes
Thanks @zfLQ2qx2, changes for `extra765` look good to me. However for `extra77` I don't agree with L39 since by default, if there is not a policy only the owner can get access so it shouldn't be a FAIL but a PASS. See first paragraph here https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-policies.html 

> only the repository owner has access to a repository

Do you agree with me that it should be PASS?

2019-12-30 15:08 UTC, zfLQ2qx2 commented
@toniblyx You are absolutely correct, I was not aware of the default. I've updated the check as you suggested.

2019-12-30 15:31 UTC, toniblyx approved these changes
LGTM

2019-12-30 15:31 UTC, merged