chore(RLS): Improve policy comparison
toniblyx/prowler pull request #6064
Opened 2024-12-09 10:22 UTC by jfagoagas

### Motivation

When an RLS policy is applied to a query, the conditions specified in the policy are evaluated for each row that the query touches. In queries affecting thousands of rows, this behavior can drastically reduce query performance, as the overhead of executing these functions adds up quickly. -- https://supabase.com/docs/guides/database/database-advisors?queryGroups=lint&lint=0003_auth_rls_initplan#the-performance-issue
### Description

Improve Postgres Row Level Security policies:
- Remove the `CASE` since it is not needed, a comparison with `null` returns `false`, so calling `current_setting('setting', True)` is more than enough.
- Wrap `current_setting` in a subquery to be executed in an `InitPlan` which will be executed just once and then the result will be cached for the rest of the rows.

### Checklist

- Are there new checks included in this PR? Yes / No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [ ] Review if the code is being covered by tests.
- [ ] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [ ] Review if backport is needed. -> **Not needed.**

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-12-09 10:23 UTC, jfagoagas commented on api/src/backend/api/rls.py
> +            (SELECT current_setting('%(tenant_setting)s', True)::uuid) = %(field_column)s
Pending to create migrations to replace these policies.

2024-12-16 09:39 UTC, vicferpoy requested changes
Thanks for the improvement! However, we are missing changes on migrations. This change will only exist for users who don't have the initial migration applied.

2024-12-16 09:39 UTC, vicferpoy commented on api/src/backend/api/rls.py
> +            # INSERT uses WITH CHECK becauseonly applies in cases where records are being added
```suggestion
            # INSERT uses WITH CHECK because only applies in cases where records are being added
```

2025-06-09 15:18 UTC, jfagoagas commented
bugbot run

2025-06-09 15:22 UTC, jfagoagas commented
bugbot run

2025-12-22 08:36 UTC, jfagoagas commented
Closing this PR as it's stale. I'll re-open it.

2025-12-22 08:36 UTC, closed without merging