docs(integrations): add integrations docs
toniblyx/prowler pull request #6269
Opened 2024-12-19 14:51 UTC by pedrooot

### Description

This pull request includes significant updates to the `docs/developer-guide/integrations.md` file to provide comprehensive guidance on creating new integrations with Prowler. The changes introduce detailed steps and best practices for developing, testing, and documenting integrations with external tools.

Documentation improvements:

* Changed the title from "Create a new integration" to "Creating a New Integration" to improve clarity.
* Added an introduction explaining the benefits and common targets for Prowler integrations, such as Slack, Jira, and AWS Security Hub.
* Outlined the steps to create a general integration, including identifying the integration purpose, reviewing Prowler’s capabilities, developing the integration, and testing it.
* Included guidelines for scripting, configuration, and creating an integration class with methods for testing connections and sending findings.
* Emphasized the importance of thorough documentation for setup, configuration, and troubleshooting to ensure maintainability and ease of onboarding.

### Checklist

- Are there new checks included in this PR? Yes / No
    - If so, do we need to update permissions for the provider? Please review this carefully.
- [ ] Review if the code is being covered by tests.
- [ ] Review if code is being documented following this specification https://github.com/google/styleguide/blob/gh-pages/pyguide.md#38-comments-and-docstrings
- [ ] Review if backport is needed.

### License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2025-01-07 11:16 UTC, puchy22 requested changes

2025-01-07 11:16 UTC, puchy22 commented on docs/developer-guide/integrations.md
> +    * Review existing integrations in the `/lib/outputs` folder for inspiration and implementation examples.
```suggestion
    * Review existing integrations in the `prowler/lib/outputs` folder for inspiration and implementation examples.
```
Maybe add a link here to consult in master directly is a good idea.

2025-01-07 11:57 UTC, pedrooot commented on docs/developer-guide/integrations.md
> +    * Review existing integrations in the `/lib/outputs` folder for inspiration and implementation examples.
Done!

2025-01-07 12:08 UTC, puchy22 commented on docs/developer-guide/integrations.md
> +    The following is the code for the `Jira` class:
```suggestion
    Here is an example with Jira integration:
```

2025-01-07 12:13 UTC, pedrooot commented on docs/developer-guide/integrations.md
> +    The following is the code for the `Jira` class:
Done!

2025-01-10 10:32 UTC, jfagoagas requested changes

2025-01-10 10:32 UTC, jfagoagas commented on docs/developer-guide/integrations.md
> +## Steps to Create a General Integration
```suggestion
## Steps to Create an Integration
```

2025-01-10 10:32 UTC, jfagoagas commented on docs/developer-guide/integrations.md
> +* Identify the best approach for the specific platform you’re targeting.
Maybe this can be moved to the intro, but I leave this up to you.

2025-01-10 11:07 UTC, pedrooot commented on docs/developer-guide/integrations.md
> +## Steps to Create a General Integration
Done

2025-01-10 11:07 UTC, pedrooot commented on docs/developer-guide/integrations.md
> +* Identify the best approach for the specific platform you’re targeting.
Done

2025-01-10 11:14 UTC, jfagoagas approved these changes

2025-01-10 11:15 UTC, puchy22 approved these changes

2025-01-10 11:15 UTC, merged