Refresh assumed role credentials to avoid role chaining limitations
toniblyx/prowler pull request #694
Opened 2020-11-20 08:46 UTC by michael-dickinson-sainsburys

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-11-20 19:39 UTC, toniblyx requested changes

2020-11-23 22:45 UTC, michael-dickinson-sainsburys commented on include/assume_role
> +    export AWS_SESSION_EXPIRATION=$(date -j -f "%Y-%m-%dT%H:%M:%SZ" "$(cat $TEMP_STS_ASSUMED_FILE | jq -r '.Credentials.Expiration')" "+%s")
Updated the code to use the same mechanism for os detection as other functions

2020-12-15 14:55 UTC, toniblyx commented on include/assume_role
> +    export AWS_SESSION_EXPIRATION=$(date -j -f "%Y-%m-%dT%H:%M:%SZ" "$(cat $TEMP_STS_ASSUMED_FILE | jq -r '.Credentials.Expiration')" "+%s")
thanks!

2020-12-15 16:28 UTC, toniblyx approved these changes

2020-12-15 16:29 UTC, merged

2020-12-15 17:00 UTC, toniblyx commented
I had to revert this change because it fails when used with Assume role options `-A account -R role`, this is the error running on a Mac:

`./prowler: line 324: ((: < (( 1608050483 + (( 3600 / 10 )) )) : syntax error: operand expected (error token is "< (( 1608050483 + (( 3600 / 10 )) )) ")`

so this command fails on a Mac: `date -j -f %Y-%m-%dT%H:%M:%SZ 2020-12-15T17:46:14+00:00 +%s`

2020-12-16 14:17 UTC, toniblyx commented
in Linux work fine.

2020-12-16 20:00 UTC, michael-dickinson-sainsburys commented
I think it is the inclusion of so many parentheses, putting together a modified version that should run (and be significantly more readable)

2020-12-16 20:07 UTC, michael-dickinson-sainsburys commented
#710 opened to try again