Add new extras check (7130) to check encryption of a SNS topic
toniblyx/prowler pull request #716
Opened 2020-12-30 08:02 UTC by mpratsch

Hi, 
I was missing the check if a SNS topic is encrypted or not.
That was an outcome of a pen test.
I'd love to see that integrated in prowler as well.

Example of a query only for eu-central-1:
![image](https://user-images.githubusercontent.com/18064721/103337762-9e780d00-4a7c-11eb-9304-623ff3109f0e.png)

Thanks Martina

2021-01-07 19:33 UTC, toniblyx commented
Thanks @mpratsch, please review my question there and also add that check to `groups/group7_extras`. Good job!

2021-01-08 08:09 UTC, mpratsch commented
> 
> 
> Thanks @mpratsch, please review my question there and also add that check to `groups/group7_extras`. Good job!

Thanks @toniblyx! Just a stupid question but where do I find your question? 🤔

2021-01-08 09:15 UTC, toniblyx requested changes

2021-01-08 09:15 UTC, toniblyx commented
I added a couple of comments to the code but I forgot to request changes, now you should see it, sorry about that :)

2021-01-08 12:36 UTC, mpratsch commented on checks/check_extra7130
> +      textInfo "$regx: No SNS topic found" "$SHORT_TOPIC" "$regx"
Ha, I had no account without a SNS topic and didn't see that one. 
It's not needed and wouldn't even work.
Thanks for that!

2021-01-08 12:54 UTC, toniblyx commented
Awesome, thanks @mpratsch!

2021-01-08 12:54 UTC, merged