New check_extra7163 Secrets Manager key rotation enabled
toniblyx/prowler pull request #937
Opened 2021-11-21 21:38 UTC by Daniel-Peladeau

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-11-21 21:38 UTC, Daniel-Peladeau commented
Check if Secrets Manager key rotation enabled.

2021-11-22 19:23 UTC, toniblyx commented
Thanks @Daniel-Peladeau, I have added some comments for you to review.

2021-11-23 10:25 UTC, toniblyx requested changes

2021-11-23 10:25 UTC, toniblyx commented on checks/check_extra7163
> +CHECK_TITLE_extra7163="[extra7163] Check if Secrets Manager key rotation enabled"
"Check if Secrets Manager key rotation is enabled" - Add `is` please.

2021-11-23 10:25 UTC, toniblyx commented on checks/check_extra7163
> +        textPass "$regx: No SecretsManager secrets found." "$regx"
`Secrets Manager` with space in between, isn't it?

2021-11-23 10:25 UTC, toniblyx commented on checks/check_extra7163
> +          KEY_ROTATION_ENABLED=$($AWSCLI secretsmanager describe-secret $PROFILE_OPT --region $regx --secret-id $secret | jq '.RotationEnabled')
if using jq, please force the output to json adding `--output json`

2021-11-24 03:31 UTC, Daniel-Peladeau commented
New commit just added with the three requested changes.

2021-11-25 14:22 UTC, merged

2021-11-25 14:22 UTC, toniblyx commented
Thanks!